import {describe,it,expect} from 'vitest';
import {validateCatalogProduct,validateCatalogPolicy,assessCatalogProduct} from '../src/catalog-contract.ts';
import {createDemoAdapters,DEMO_CREATED_AT} from '../src/demo-catalog.ts';
for(const adapter of createDemoAdapters())describe(`shared catalog contract: ${adapter.policy.sourceId}`,()=>{
 it('normalizes bounded USD/US synthetic products',async()=>{const rows=await adapter.search({text:'',limit:20});expect(rows.length).toBe(2);for(const row of rows){expect(validateCatalogProduct(row,adapter.policy,DEMO_CREATED_AT)).toEqual(row);expect(row.productUrl).toBeNull();expect(row.image.url).toMatch(/^\/demo-catalog\//);expect(assessCatalogProduct(row,adapter.policy,DEMO_CREATED_AT,{size:row.size,destination:'US-CA'}).eligible).toBe(false);}});
 it('resolves exact supplied IDs and never invents products or variants',async()=>{const [row]=await adapter.search({text:'',limit:1});expect(await adapter.get(row!.productId,row!.variantId)).toEqual(row);expect(await adapter.get(row!.productId,'invented')).toBeNull();expect(await adapter.get('invented',row!.variantId)).toBeNull();});
 it('filters and copies results without mutating the catalog or policy',async()=>{const rows=await adapter.search({text:'',limit:1});const original=rows[0]!.name;rows[0]!.name='tampered';const p=adapter.policy;p.capabilities.externalCheckout=true;expect((await adapter.search({text:'',limit:1}))[0]!.name).toBe(original);expect(adapter.policy.capabilities.externalCheckout).toBe(false);expect(await adapter.search({text:'no such garment',limit:1})).toEqual([]);});
 it.each([0,21,1.5])('rejects search limit %s',async limit=>{await expect(adapter.search({text:'',limit})).rejects.toThrow('held');});
});
describe('catalog evidence and permission guards',()=>{
 const adapter=createDemoAdapters()[0]!;
 const livePolicy={...adapter.policy,synthetic:false,permittedHosts:['shop.example.com'],imageHosts:['images.example.com'],rightsReferences:['written-license-v1'],capabilities:{...adapter.policy.capabilities,externalCheckout:true}};
 async function live(){const [p]=await adapter.search({text:'',limit:1});return{...p!,sourceId:livePolicy.sourceId,synthetic:false,productUrl:'https://shop.example.com/product/dress',image:{url:'https://images.example.com/dress.jpg',rightsReference:'written-license-v1'},availability:'available' as const,delivery:{status:'eligible' as const,destination:'US-CA'}};}
 it('permits fully evidenced product but makes no recommendation approval',async()=>{const p=await live();expect(assessCatalogProduct(p,livePolicy,DEMO_CREATED_AT,{size:'M',destination:'US-CA'})).toMatchObject({eligible:true,reasons:[]});});
 it.each(['https://evil.example/product','http://shop.example.com/product','https://user:secret@shop.example.com/product','https://shop.example.com:123/product','https://shop.example.com/product#fragment'])('rejects unapproved or unsafe product URLs',async productUrl=>{const p=await live();expect(()=>validateCatalogProduct({...p,productUrl},livePolicy,DEMO_CREATED_AT)).toThrow('held');});
 it.each([-1,1.5,NaN,Infinity,10000001])('rejects invalid cents %s',async priceCents=>{const p=await live();expect(()=>validateCatalogProduct({...p,priceCents},livePolicy,DEMO_CREATED_AT)).toThrow('held');});
 it('keeps price, freshness, size and destination uncertainty explicit',async()=>{const p=await live();const result=assessCatalogProduct({...p,priceCents:null},livePolicy,DEMO_CREATED_AT+86400001,{size:'L',destination:'US-NY'});expect(result.eligible).toBe(false);expect(result.reasons).toEqual(['stale','price-unknown','size-unverified','delivery-unverified']);});
 it('rejects unknown image rights and future retrieval evidence',async()=>{const p=await live();expect(()=>validateCatalogProduct({...p,image:{...p.image,rightsReference:'invented'}},livePolicy,DEMO_CREATED_AT)).toThrow();expect(()=>validateCatalogProduct({...p,checkedAt:DEMO_CREATED_AT+1},livePolicy,DEMO_CREATED_AT)).toThrow();});
 it('refuses synthetic checkout capability',()=>{expect(()=>validateCatalogPolicy({...adapter.policy,capabilities:{...adapter.policy.capabilities,externalCheckout:true}})).toThrow();});
});
