import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {PreparedLiveTranscription,LIVE_TRANSCRIPTION_ENABLED} from '../src/live-transcription.ts';
import {NotebookState} from '../src/notebook-state.ts';
import {PartialNoteCoordinator} from '../src/partial-note-coordinator.ts';
const ack={type:'session.updated',session:{type:'transcription',audio:{input:{format:{type:'audio/pcm',rate:24000},transcription:{model:'gpt-live-transcribe'},turn_detection:null}}}};
const delta=(text='green',event_id='ev1',item_id='item1')=>({type:'conversation.item.input_audio_transcription.delta',event_id,item_id,content_index:0,delta:text});
const done=(text='green',event_id='done1',item_id='item1')=>({type:'conversation.item.input_audio_transcription.completed',event_id,item_id,content_index:0,transcript:text});
function setup(emit=vi.fn()) {const wire={bufferedAmount:0,send:vi.fn(()=>true),close:vi.fn()},controller=new AbortController(),stopped=vi.fn();const stream=new PreparedLiveTranscription({simulation:true,wire,signal:controller.signal,emit,stopped});return{wire,controller,stopped,stream,emit};}
function ready(){const s=setup();s.stream.receive(ack);s.stream.beginTurn('turn1');return s;}
function commit(s:ReturnType<typeof ready>){for(let i=0;i<5;i++)s.stream.append(new ArrayBuffer(960),i);s.stream.commit();s.stream.receive({type:'input_audio_buffer.committed',event_id:'commit1',item_id:'item1'});}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('disabled live transcription protocol',()=>{
 it('refuses default live use before sending anything',()=>{const wire={bufferedAmount:0,send:vi.fn(()=>true),close:vi.fn()};expect(LIVE_TRANSCRIPTION_ENABLED).toBe(false);expect(()=>new PreparedLiveTranscription({wire,signal:new AbortController().signal,emit:vi.fn(),stopped:vi.fn()})).toThrow('disabled');expect(wire.send).not.toHaveBeenCalled();});
 it('sends transcription-only configuration and waits for acknowledgment',()=>{const s=setup();expect(s.wire.send.mock.calls[0]).toMatchObject([ {type:'session.update',session:ack.session} ]);expect(s.stream.beginTurn('turn1')).toBe(false);s.stream.receive(ack);expect(s.stream.beginTurn('turn1')).toBe(true);});
 it('holds incompatible configuration',()=>{const s=setup();s.stream.receive({...ack,session:{type:'realtime'}});expect(s.stopped).toHaveBeenCalledWith('configuration-mismatch');});
 it('emits cumulative user partials before commit',()=>{const s=ready();s.stream.receive(delta());s.stream.receive(delta(' blue','ev2'));expect(s.emit.mock.calls.map(c=>c[0].text)).toEqual(['green','green blue']);expect(s.emit.mock.calls[0]![0].final).toBe(false);});
 it('deduplicates provider events and accepts corrected final text',()=>{const s=ready();s.stream.receive(delta());expect(s.stream.receive(delta())).toBe(false);s.stream.receive(done('blue'));expect(s.emit).toHaveBeenCalledTimes(2);expect(s.emit.mock.calls[1]![0]).toMatchObject({text:'blue',final:true,sequence:2});expect(s.stream.receive(delta('late','late'))).toBe(false);});
 it('maps committed IDs and ignores an old completion after a new turn',()=>{const s=ready();s.stream.receive(delta());commit(s);expect(s.stream.beginTurn('turn2')).toBe(true);s.stream.receive(delta('blue','ev2','item2'));s.stream.receive(done('old green'));expect(s.emit.mock.calls.map(c=>c[0].text)).toEqual(['green','blue']);});
 it('refuses new input until the commit is acknowledged',()=>{const s=ready();for(let i=0;i<5;i++)s.stream.append(new ArrayBuffer(960),i);expect(s.stream.commit()).toBe(true);expect(s.stream.beginTurn('turn2')).toBe(false);expect(s.stream.append(new ArrayBuffer(960),5)).toBe(false);});
 it('fails closed on mismatched committed item',()=>{const s=ready();s.stream.receive(delta());for(let i=0;i<5;i++)s.stream.append(new ArrayBuffer(960),i);s.stream.commit();s.stream.receive({type:'input_audio_buffer.committed',event_id:'commit',item_id:'wrong'});expect(s.stopped).toHaveBeenCalledWith('item-mismatch');});
 it.each([959,962])('rejects invalid %s-byte microphone frames',bytes=>{const s=ready();expect(s.stream.append(new ArrayBuffer(bytes),0)).toBe(false);expect(s.wire.close).toHaveBeenCalledTimes(1);});
 it('holds out-of-order microphone frames and short turns',()=>{const s=ready();expect(s.stream.append(new ArrayBuffer(960),1)).toBe(false);const other=ready();expect(other.stream.commit()).toBe(false);expect(other.stopped).toHaveBeenCalledWith('empty-or-short-turn');});
 it('applies transport backpressure without retry',()=>{const s=ready();s.wire.bufferedAmount=65537;expect(s.stream.append(new ArrayBuffer(960),0)).toBe(false);expect(s.stopped).toHaveBeenCalledWith('transport-held');});
 it.each(['error','conversation.item.input_audio_transcription.failed'])('redacts %s provider failures',type=>{const s=ready();s.stream.receive({type,error:{message:'private sentinel'}});expect(s.stopped).toHaveBeenCalledWith('provider-failed');expect(JSON.stringify(s.stream.snapshot())).not.toContain('sentinel');});
 it('enforces configuration and overall deadlines',async()=>{const s=setup();await vi.advanceTimersByTimeAsync(5000);expect(s.stopped).toHaveBeenCalledWith('configuration-timeout');const other=ready();await vi.advanceTimersByTimeAsync(85000);expect(other.stopped).toHaveBeenCalledWith('time-limit');});
 it('clears content and ignores late events after cancellation',()=>{const s=ready();s.stream.receive(delta('private sentinel'));s.controller.abort();expect(s.stream.receive(done())).toBe(false);expect(s.wire.close).toHaveBeenCalledTimes(1);expect(JSON.stringify(s.stream.snapshot())).not.toContain('sentinel');});
 it('holds oversized text, invalid events and consumer failures',()=>{const s=ready();s.stream.receive(delta('x'.repeat(4001)));expect(s.stopped).toHaveBeenCalledWith('transcript-bound');const other=ready();other.stream.receive(null);expect(other.stopped).toHaveBeenCalledWith('invalid-event');const third=setup(vi.fn(()=>{throw Error('secret');}));third.stream.receive(ack);third.stream.beginTurn('turn1');third.stream.receive(delta());expect(third.stopped).toHaveBeenCalledWith('consumer-held');});
 it('feeds a synthetic extractor during speech and protects touch edits',async()=>{const notebook=new NotebookState(),coordinator=new PartialNoteCoordinator({notebook,extract:async input=>[{field:'color',value:input.text,evidence:input.text,confirmed:true}],changed:()=>{}});const s=setup(vi.fn(event=>{coordinator.accept(event);}));s.stream.receive(ack);s.stream.beginTurn('turn1');s.stream.receive(delta());await vi.advanceTimersByTimeAsync(100);expect(notebook.snapshot().notes.color.status).toBe('tentative');notebook.edit('color','Red');s.stream.receive(delta(' blue','ev2'));await vi.advanceTimersByTimeAsync(100);expect(notebook.snapshot().notes.color.value).toBe('Red');s.stream.end();coordinator.cancel();});
});

describe('transcription bounds and cleanup',()=>{
 it('records requested cleanup without claiming remote verification',()=>{const s=ready();s.stream.disconnected();s.stream.end();expect(s.wire.close).toHaveBeenCalledTimes(1);expect(s.stream.snapshot()).toMatchObject({cleanupRequested:true,cleanupFailed:false,remoteCleanupVerified:false});});
 it('reports failed cleanup with no raw error text',()=>{const s=ready();s.wire.close.mockImplementation(()=>{throw Error('private credential sentinel');});expect(()=>s.stream.end()).not.toThrow();expect(s.stopped).toHaveBeenCalledWith('cleanup-unverified');expect(JSON.stringify(s.stream.snapshot())).not.toContain('sentinel');});
 it('does not send configuration when already aborted',()=>{const controller=new AbortController();controller.abort();const wire={bufferedAmount:0,send:vi.fn(()=>true),close:vi.fn()};new PreparedLiveTranscription({simulation:true,wire,signal:controller.signal,emit:vi.fn(),stopped:vi.fn()});expect(wire.send).not.toHaveBeenCalled();expect(wire.close).toHaveBeenCalledTimes(1);});
 it('holds unexpected content indexes and reused turn names',()=>{const s=ready();s.stream.receive({...delta(),content_index:1});expect(s.stopped).toHaveBeenCalledWith('invalid-content');const other=ready();commit(other);expect(other.stream.beginTurn('turn1')).toBe(false);expect(other.stopped).toHaveBeenCalledWith('turn-bound');});
 it('holds total transcript and event limits',()=>{const s=ready();s.stream.receive(delta('x'.repeat(4000)));s.stream.receive(delta('x','ev2'));expect(s.stopped).toHaveBeenCalledWith('transcript-bound');const other=ready();for(let i=0;i<257;i++)other.stream.receive(delta('x',`ev_${i}`));expect(other.stopped).toHaveBeenCalledWith('event-bound');});
 it('caps audio and stops accepting subsequent frames',()=>{const s=ready();for(let i=0;i<4251;i++)s.stream.append(new ArrayBuffer(960),i);expect(s.stopped).toHaveBeenCalledWith('audio-bound');expect(s.stream.snapshot().audioBytes).toBe(4080000);expect(s.stream.append(new ArrayBuffer(960),4251)).toBe(false);});
});
