import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {NoteSessionProbe} from '../src/note-session-probe.ts';
import {NotebookState} from '../src/notebook-state.ts';
const ack={type:'session.updated',session:{type:'transcription',audio:{input:{format:{type:'audio/pcm',rate:24000},transcription:{model:'gpt-live-transcribe'},turn_detection:null}}}};
const delta=(text='green',event_id='ev1',item_id='item1')=>({type:'conversation.item.input_audio_transcription.delta',event_id,item_id,content_index:0,delta:text});
function setup(extract:(input:{text:string},signal:AbortSignal)=>Promise<unknown>=async input=>[{field:'color',value:input.text,evidence:input.text,confirmed:true}]){
 let accept!:(pcm:ArrayBuffer)=>boolean,onStop!:(reason:string)=>void;
 const capture={start:vi.fn(async(a:(pcm:ArrayBuffer)=>boolean,s:(reason:string)=>void)=>{accept=a;onStop=s;return true;}),stop:vi.fn()},wire={bufferedAmount:0,send:vi.fn(()=>true),close:vi.fn()},changed=vi.fn(),invalidated=vi.fn(),turnReady=vi.fn(),notebook=new NotebookState();
 const probe=new NoteSessionProbe({simulation:true,notebook,capture,wire,changed,invalidated,turnReady,extract});
 return{capture,wire,changed,invalidated,turnReady,notebook,probe,frame:()=>accept(new ArrayBuffer(960)),captureStopped:()=>onStop('device-ended')};
}
async function ready(){const s=setup();s.probe.receive(ack);await s.probe.beginTurn('turn1');return s;}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('simulated note session ownership',()=>{
 it('does not acquire microphone before configuration',async()=>{const s=setup();expect(await s.probe.beginTurn('turn1')).toBe(false);expect(s.capture.start).not.toHaveBeenCalled();s.probe.end();});
 it('feeds simulated frames and partials through extraction before turn end',async()=>{const s=await ready();expect(s.frame()).toBe(true);s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.status).toBe('tentative');expect(s.probe.acknowledgeRendered(s.changed.mock.calls[0]![0])).toBe(true);s.probe.end();});
 it('protects a touch edit from later fragments',async()=>{const s=await ready();s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);s.notebook.edit('color','Red');s.probe.receive(delta(' blue','ev2'));await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.value).toBe('Red');s.probe.end();});
 it.each(['end','clear','disconnect','capture','provider'])('cancels media and pending extraction on %s',async reason=>{let resolve!:(v:unknown)=>void,signal!:AbortSignal;const s=setup(async(_input,sig)=>{signal=sig;return new Promise(r=>{resolve=r;});});s.probe.receive(ack);await s.probe.beginTurn('turn1');s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);switch(reason){case'end':s.probe.end();break;case'clear':s.notebook.clear();break;case'disconnect':s.probe.disconnected();break;case'capture':s.captureStopped();break;default:s.probe.receive({type:'error'});}expect(signal.aborted).toBe(true);resolve([{field:'color',value:'Green',evidence:'green',confirmed:true}]);await vi.advanceTimersByTimeAsync(0);expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.probe.snapshot().ended).toBe(true);expect(s.wire.close).toHaveBeenCalledTimes(1);expect(s.frame()).toBe(false);});
 it('stops extraction and capture after the configuration deadline',async()=>{const s=setup();await vi.advanceTimersByTimeAsync(5000);expect(s.probe.snapshot().reason).toBe('configuration-timeout');expect(s.capture.stop).toHaveBeenCalled();});
 it('stops the source before committing and keeps old callbacks obsolete',async()=>{const s=await ready();for(let i=0;i<5;i++)s.frame();expect(s.probe.commit()).toBe(true);s.captureStopped();expect(s.probe.snapshot().ended).toBe(false);expect(s.frame()).toBe(false);s.probe.receive({type:'input_audio_buffer.committed',event_id:'commit1',item_id:'item1'});expect(await s.probe.beginTurn('turn2')).toBe(false);s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'item1',content_index:0,transcript:'green'});await vi.advanceTimersByTimeAsync(100);expect(await s.probe.beginTurn('turn2')).toBe(true);expect(s.frame()).toBe(true);s.probe.end();});
 it('releases a source acquired after the session ended',async()=>{const s=setup();let resolve!:(v:boolean)=>void;s.capture.start.mockImplementation(()=>new Promise(r=>{resolve=r;}));s.probe.receive(ack);const pending=s.probe.beginTurn('turn1');s.probe.end();resolve(true);expect(await pending).toBe(false);expect(s.capture.stop).toHaveBeenCalledTimes(2);});
 it('holds extraction failures without leaking provider error text',async()=>{const s=setup(async()=>{throw Error('private sentinel');});s.probe.receive(ack);await s.probe.beginTurn('turn1');s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);expect(s.probe.snapshot().reason).toBe('extraction-held');expect(JSON.stringify(s.probe.snapshot())).not.toContain('sentinel');});
 it('holds display failures and rejects late render receipts',async()=>{const s=await ready();s.changed.mockImplementation(()=>{throw Error('display');});s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);expect(s.probe.snapshot().reason).toBe('display-held');expect(s.probe.acknowledgeRendered(1)).toBe(false);});
 it('ends only once and never reconnects automatically',async()=>{const s=await ready();s.probe.end();s.probe.end();s.probe.disconnected();expect(s.wire.close).toHaveBeenCalledTimes(1);expect(s.probe.receive(ack)).toBe(false);expect(await s.probe.beginTurn('next')).toBe(false);});
});

describe('session failure boundaries',()=>{
 it('refuses default construction without touching capture or transport',()=>{const capture={start:vi.fn(async()=>true),stop:vi.fn()},wire={bufferedAmount:0,send:vi.fn(()=>true),close:vi.fn()};expect(()=>new NoteSessionProbe({notebook:new NotebookState(),capture,wire,extract:async()=>[],changed:vi.fn()})).toThrow('disabled');expect(wire.send).not.toHaveBeenCalled();expect(capture.start).not.toHaveBeenCalled();});
 it('holds capture denial and capture cleanup failure',async()=>{const s=setup();s.capture.start.mockResolvedValue(false);s.probe.receive(ack);expect(await s.probe.beginTurn('turn1')).toBe(false);expect(s.probe.snapshot().reason).toBe('capture-unavailable');const other=await ready();other.capture.stop.mockImplementation(()=>{throw Error('private');});other.probe.end();expect(other.probe.snapshot().reason).toBe('capture-cleanup-held');});
 it('records failed transport cleanup without claiming remote completion',async()=>{const s=await ready();s.wire.close.mockImplementation(()=>{throw Error('private');});s.probe.end();expect(s.probe.snapshot().reason).toBe('cleanup-unverified');expect(s.probe.snapshot().transcription?.remoteCleanupVerified).toBe(false);});
 it('cancels source acquisition when its overall session deadline expires',async()=>{const s=setup();let resolve!:(v:boolean)=>void;s.capture.start.mockImplementation(()=>new Promise(r=>{resolve=r;}));s.probe.receive(ack);const pending=s.probe.beginTurn('turn1');await vi.advanceTimersByTimeAsync(85000);resolve(true);expect(await pending).toBe(false);expect(s.probe.snapshot().reason).toBe('time-limit');});
 it('releases nothing when initial configuration send fails synchronously',()=>{const capture={start:vi.fn(async()=>true),stop:vi.fn()},wire={bufferedAmount:0,send:vi.fn(()=>false),close:vi.fn()},notebook=new NotebookState();const probe=new NoteSessionProbe({simulation:true,notebook,capture,wire,extract:async()=>[],changed:vi.fn()});expect(probe.snapshot().reason).toBe('transport-held');expect(wire.close).toHaveBeenCalledTimes(1);expect(capture.start).not.toHaveBeenCalled();});
});

describe('revision-bound customer commands',()=>{
 it('publishes an edit and invalidates an existing look check immediately',()=>{const s=setup();const ticket=s.notebook.beginCheck();s.notebook.completeCheck(ticket,{outcome:'passed',reason:'fixture'});expect(s.probe.edit('color',' Blue ',0)).toBe(true);expect(s.notebook.snapshot().notes.color).toMatchObject({value:'Blue',status:'confirmed',source:'touch',revision:1});expect(s.notebook.canPresent()).toBe(false);expect(s.invalidated).toHaveBeenCalledTimes(1);s.probe.end();});
 it('rejects stale edit and confirmation without publishing',()=>{const s=setup();s.probe.edit('color','Blue',0);expect(s.probe.edit('color','Red',0)).toBe(false);expect(s.probe.confirm('color',0)).toBe(false);expect(s.invalidated).toHaveBeenCalledTimes(1);expect(s.notebook.snapshot().notes.color.value).toBe('Blue');s.probe.end();});
 it('confirms only the current nonempty tentative value',async()=>{const s=await ready();expect(s.probe.confirm('color',0)).toBe(false);s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);const revision=s.notebook.snapshot().notes.color.revision;expect(s.probe.confirm('color',revision)).toBe(true);expect(s.notebook.snapshot().notes.color).toMatchObject({value:'green',status:'confirmed',source:'touch'});s.probe.end();});
 it('allows clearing a note and refuses invalid fields, revisions and oversized text',()=>{const s=setup();expect(s.probe.edit('color','Blue',0)).toBe(true);expect(s.probe.edit('color',' ',1)).toBe(true);expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.probe.confirm('color',2)).toBe(false);expect(s.probe.edit('unknown' as any,'x',0)).toBe(false);expect(s.probe.edit('color','x',NaN)).toBe(false);expect(s.probe.edit('color','x'.repeat(161),2)).toBe(false);s.probe.end();expect(s.probe.edit('color','x',0)).toBe(false);});
 it('holds and clears the session if publishing a customer edit fails',()=>{const s=setup();s.invalidated.mockImplementation(()=>{throw Error('private');});expect(s.probe.edit('color','Blue',0)).toBe(false);expect(s.probe.snapshot().reason).toBe('display-held');expect(s.notebook.snapshot().notes.color.status).toBe('missing');});
 it('protects a server edit against extraction already in flight',async()=>{let resolve!:(v:unknown)=>void;const s=setup(async()=>new Promise(r=>{resolve=r;}));s.probe.receive(ack);await s.probe.beginTurn('turn1');s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);expect(s.probe.edit('color','Blue',0)).toBe(true);resolve([{field:'color',value:'green',evidence:'green',confirmed:false}]);await vi.advanceTimersByTimeAsync(0);expect(s.notebook.snapshot().notes.color.value).toBe('Blue');s.probe.end();});
});

describe('provider commit readiness publication',()=>{
 it('waits for matching commit and final extraction before naming the original turn',async()=>{const s=await ready();for(let i=0;i<5;i++)s.frame();s.probe.commit();s.probe.receive({type:'input_audio_buffer.committed',event_id:'c1',item_id:'i1'});expect(s.turnReady).not.toHaveBeenCalled();s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'i1',content_index:0,transcript:'green'});expect(s.turnReady).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(100);expect(s.turnReady).toHaveBeenCalledWith('turn1');expect(s.notebook.snapshot().notes.color.value).toBe('green');s.probe.end();});
 it('holds readiness publisher failure and clears the owned session',async()=>{const s=await ready();for(let i=0;i<5;i++)s.frame();s.probe.commit();s.turnReady.mockImplementation(()=>{throw Error('private');});s.probe.receive({type:'input_audio_buffer.committed',event_id:'c1',item_id:'i1'});s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'i1',content_index:0,transcript:'green'});await vi.advanceTimersByTimeAsync(100);expect(s.probe.snapshot().reason).toBe('display-held');});
 it('does not release the next turn while final extraction is unresolved',async()=>{let resolve!:(v:unknown)=>void;const s=setup(async()=>new Promise(r=>{resolve=r;}));s.probe.receive(ack);await s.probe.beginTurn('turn1');for(let i=0;i<5;i++)s.frame();s.probe.commit();s.probe.receive({type:'input_audio_buffer.committed',event_id:'c1',item_id:'i1'});s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'i1',content_index:0,transcript:'green'});await vi.advanceTimersByTimeAsync(100);expect(s.turnReady).not.toHaveBeenCalled();resolve([{field:'color',value:'green',evidence:'green',confirmed:false}]);await vi.advanceTimersByTimeAsync(0);expect(s.turnReady).toHaveBeenCalledTimes(1);s.probe.end();});
});

describe('final extraction readiness edge cases',()=>{
 it('releases an unchanged final transcript after its partial already applied',async()=>{const s=await ready();s.probe.receive(delta());await vi.advanceTimersByTimeAsync(100);for(let i=0;i<5;i++)s.frame();s.probe.commit();s.probe.receive({type:'input_audio_buffer.committed',event_id:'c1',item_id:'item1'});s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'item1',content_index:0,transcript:'green'});await vi.advanceTimersByTimeAsync(100);expect(s.turnReady).toHaveBeenCalledTimes(1);s.probe.end();});
 it('waits for commit if final extraction settles first',async()=>{const s=await ready();for(let i=0;i<5;i++)s.frame();s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'item1',content_index:0,transcript:'green'});await vi.advanceTimersByTimeAsync(100);expect(s.turnReady).not.toHaveBeenCalled();s.probe.commit();s.probe.receive({type:'input_audio_buffer.committed',event_id:'c1',item_id:'item1'});expect(s.turnReady).toHaveBeenCalledWith('turn1');s.probe.end();});
 it('releases a valid final extraction containing no styling preferences',async()=>{const s=setup(async()=>[]);s.probe.receive(ack);await s.probe.beginTurn('turn1');for(let i=0;i<5;i++)s.frame();s.probe.commit();s.probe.receive({type:'input_audio_buffer.committed',event_id:'c1',item_id:'i1'});s.probe.receive({type:'conversation.item.input_audio_transcription.completed',event_id:'f1',item_id:'i1',content_index:0,transcript:'hello'});await vi.advanceTimersByTimeAsync(100);expect(s.turnReady).toHaveBeenCalledWith('turn1');expect(s.notebook.snapshot().notes.color.status).toBe('missing');s.probe.end();});
});
