import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {NoteBrowserController} from '../src/note-browser-controller.ts';
import {encodeNoteUpdate} from '../src/note-update-wire.ts';
import {NotebookState} from '../src/notebook-state.ts';
const ready={version:1,type:'ready',sessionId:'s1',simulation:true,liveEnabled:false};
function setup(){const socket={send:vi.fn(),close:vi.fn(),bufferedAmount:0},changed=vi.fn(),controller=new NoteBrowserController({simulation:true,socket,changed}),notebook=new NotebookState();return{socket,changed,controller,notebook,update:(seq=1,receipt:number|null=null)=>encodeNoteUpdate('s1',seq,notebook.snapshot(),receipt),ack:(sequence=1)=>controller.receive({version:1,type:'accepted',sessionId:'s1',sequence})};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('disabled browser notebook controller',()=>{
 it('requires explicit simulation before using a socket',()=>{const socket={send:vi.fn(),close:vi.fn(),bufferedAmount:0};expect(()=>new NoteBrowserController({socket,changed:vi.fn()})).toThrow('disabled');expect(socket.send).not.toHaveBeenCalled();});
 it('edits and confirms the exact server revision without optimistic notes',()=>{const s=setup();s.controller.receive(ready);s.notebook.capture({session:1,field:'color',sequence:1,baseRevision:0,value:'green',confirmed:false});s.controller.receive(s.update());expect(s.controller.edit('color','Blue')).toBe(true);expect(JSON.parse(s.socket.send.mock.calls[0]![0])).toMatchObject({type:'edit',expectedRevision:1,value:'Blue'});expect(s.controller.snapshot().notes!.notes.color.value).toBe('green');expect(s.controller.confirm('color')).toBe(false);s.ack();expect(s.controller.confirm('color')).toBe(true);expect(JSON.parse(s.socket.send.mock.calls[1]![0])).toMatchObject({type:'confirm',expectedRevision:1});s.controller.stop();});
 it('holds a render receipt until its pending command is accepted',()=>{const s=setup();s.controller.receive(ready);s.controller.begin('turn1');s.notebook.edit('color','Blue');s.controller.receive(s.update(1,9));expect(s.controller.rendered(1)).toBe(false);s.ack();expect(s.controller.rendered(1)).toBe(true);expect(JSON.parse(s.socket.send.mock.calls[1]![0])).toMatchObject({type:'rendered',receipt:9,sequence:2});s.ack(2);expect(s.controller.rendered(1)).toBe(false);s.controller.stop();});
 it('rejects a stale UI receipt after a newer display arrives',()=>{const s=setup();s.controller.receive(ready);s.controller.receive(s.update(1,1));s.notebook.edit('color','Blue');s.controller.receive(s.update(2,2));expect(s.controller.rendered(1)).toBe(false);expect(s.controller.rendered(2)).toBe(true);s.controller.stop();});
 it.each(['wrong-session','wrong-sequence','unsolicited','extra','replay'])('clears notes on invalid acknowledgment %s',kind=>{const s=setup();s.controller.receive(ready);s.notebook.edit('color','private sentinel');s.controller.receive(s.update());const value:any={version:1,type:'accepted',sessionId:'s1',sequence:1};if(kind!=='unsolicited')s.controller.begin('turn1');if(kind==='wrong-session')value.sessionId='other';if(kind==='wrong-sequence')value.sequence=2;if(kind==='extra')value.owner=true;if(kind==='replay')s.ack();expect(s.controller.receive(value)).toBe(false);expect(s.controller.snapshot().notes).toBeNull();expect(s.changed).toHaveBeenLastCalledWith(null);expect(s.socket.close).toHaveBeenCalledTimes(1);});
 it('closes on configuration and command timeout without reconnecting',async()=>{const s=setup();await vi.advanceTimersByTimeAsync(5000);expect(s.controller.snapshot().ended).toBe(true);const t=setup();t.controller.receive(ready);t.controller.begin('turn1');await vi.advanceTimersByTimeAsync(5000);expect(t.controller.snapshot().ended).toBe(true);expect(t.socket.send).toHaveBeenCalledTimes(1);});
 it('enforces the whole-session deadline after ready',async()=>{const s=setup();s.controller.receive(ready);await vi.advanceTimersByTimeAsync(85000);expect(s.controller.snapshot().ended).toBe(true);});
 it('holds malformed or replayed updates and ignores late events after disconnect',()=>{const s=setup();s.controller.receive(ready);s.controller.receive(s.update());expect(s.controller.receive(s.update())).toBe(false);expect(s.controller.receive(ready)).toBe(false);expect(s.socket.close).toHaveBeenCalledTimes(1);expect(s.controller.snapshot().notes).toBeNull();});
 it('holds a failed send or an overflowing socket',()=>{const s=setup();s.controller.receive(ready);s.socket.send.mockImplementation(()=>{throw Error('private');});expect(s.controller.begin('t')).toBe(false);expect(s.controller.snapshot().ended).toBe(true);const t=setup();t.controller.receive(ready);t.socket.bufferedAmount=65537;expect(t.controller.begin('t')).toBe(false);expect(t.socket.send).not.toHaveBeenCalled();});
 it('clears notes if the UI callback fails',()=>{const s=setup();s.controller.receive(ready);s.changed.mockImplementation(()=>{throw Error('UI');});expect(s.controller.receive(s.update())).toBe(false);expect(s.controller.snapshot().notes).toBeNull();});
 it('does not mutate unknown fields or confirm missing values',()=>{const s=setup();s.controller.receive(ready);s.controller.receive(s.update());expect(s.controller.confirm('color')).toBe(false);expect(s.controller.edit('profile' as any,'x')).toBe(false);expect(s.controller.edit('color','x'.repeat(161))).toBe(false);expect(s.controller.begin('../bad')).toBe(false);expect(s.socket.send).not.toHaveBeenCalled();s.controller.stop();});
});

describe('simulated browser PCM transport',()=>{
 it('sends PCM only after begin acknowledgment and stops before commit',()=>{const s=setup();s.controller.receive(ready);const pcm=new ArrayBuffer(960);expect(s.controller.audio(pcm)).toBe(false);s.controller.begin('t1');expect(s.controller.audio(pcm)).toBe(false);s.ack();expect(s.controller.audio(pcm)).toBe(true);expect((s.socket.send.mock.calls[1]![0] as ArrayBuffer).byteLength).toBe(968);expect(s.controller.begin('t2')).toBe(false);expect(s.controller.commit()).toBe(true);expect(s.controller.audio(pcm)).toBe(false);s.ack(2);s.controller.receive({version:1,type:'turn-ready',sessionId:'s1',turnId:'t1'});s.controller.begin('t2');s.ack(3);expect(s.controller.audio(pcm)).toBe(true);expect(new DataView(s.socket.send.mock.calls.at(-1)![0]).getUint32(4)).toBe(1);s.controller.stop();expect(s.controller.audio(pcm)).toBe(false);});
 it('ends when a PCM frame is malformed or socket backlog exceeds the bound',()=>{const s=setup();s.controller.receive(ready);s.controller.begin('t1');s.ack();expect(s.controller.audio(new ArrayBuffer(1))).toBe(false);expect(s.controller.snapshot().ended).toBe(true);const t=setup();t.controller.receive(ready);t.controller.begin('t1');t.ack();t.socket.bufferedAmount=65537;expect(t.controller.audio(new ArrayBuffer(960))).toBe(false);expect(t.controller.snapshot().ended).toBe(true);});
});

describe('audio command exhaustion',()=>{
 it('closes rather than leaving a server turn active when commit cannot be sent',()=>{const s=setup();s.controller.receive(ready);s.notebook.edit('color','green');s.controller.receive(s.update());s.controller.begin('t1');s.ack(1);for(let i=2;i<=256;i++){expect(s.controller.confirm('color')).toBe(true);s.ack(i);}expect(s.controller.commit()).toBe(false);expect(s.controller.snapshot().ended).toBe(true);expect(s.controller.audio(new ArrayBuffer(960))).toBe(false);expect(s.socket.close).toHaveBeenCalledTimes(1);});
});

describe('provider-ready turn progression',()=>{
 it('requires both command and provider acknowledgment before another turn',()=>{const s=setup();s.controller.receive(ready);s.controller.begin('t1');s.ack();s.controller.commit();s.ack(2);expect(s.controller.begin('t2')).toBe(false);expect(s.controller.snapshot().awaitingProvider).toBe(true);expect(s.controller.receive({version:1,type:'turn-ready',sessionId:'s1',turnId:'t1'})).toBe(true);expect(s.controller.begin('t1')).toBe(false);expect(s.controller.begin('t2')).toBe(true);s.controller.stop();});
 it('accepts provider readiness before the command ack but holds the next command slot',()=>{const s=setup();s.controller.receive(ready);s.controller.begin('t1');s.ack();s.controller.commit();s.controller.receive({version:1,type:'turn-ready',sessionId:'s1',turnId:'t1'});expect(s.controller.begin('t2')).toBe(false);s.ack(2);expect(s.controller.begin('t2')).toBe(true);s.controller.stop();});
 it.each(['wrong-turn','wrong-session','unsolicited','extra','duplicate'])('holds invalid readiness %s',kind=>{const s=setup();s.controller.receive(ready);const event:any={version:1,type:'turn-ready',sessionId:'s1',turnId:'t1'};if(kind!=='unsolicited'){s.controller.begin('t1');s.ack();s.controller.commit();}if(kind==='wrong-turn')event.turnId='other';if(kind==='wrong-session')event.sessionId='other';if(kind==='extra')event.owner=true;if(kind==='duplicate')s.controller.receive(event);expect(s.controller.receive(event)).toBe(false);expect(s.controller.snapshot().ended).toBe(true);});
 it('ends when provider readiness does not arrive after a command acknowledgment',async()=>{const s=setup();s.controller.receive(ready);s.controller.begin('t1');s.ack();s.controller.commit();s.ack(2);await vi.advanceTimersByTimeAsync(5000);expect(s.controller.snapshot().ended).toBe(true);expect(s.controller.snapshot().notes).toBeNull();});
});

describe('bounded repeated turn identities',()=>{
 it('does not reuse turn IDs or exceed the existing sixteen-turn bound',()=>{const s=setup();s.controller.receive(ready);for(let i=1;i<=16;i++){expect(s.controller.begin(`t${i}`)).toBe(true);s.ack(i*2-1);expect(s.controller.commit()).toBe(true);s.ack(i*2);expect(s.controller.receive({version:1,type:'turn-ready',sessionId:'s1',turnId:`t${i}`})).toBe(true);}expect(s.controller.begin('t1')).toBe(false);expect(s.controller.begin('t17')).toBe(false);s.controller.stop();});
});

describe('display-bound touch command versions',()=>{
 it.each(['session','epoch','revision'])('refuses a stale %s for edit and confirmation without sending',kind=>{const s=setup();s.controller.receive(ready);s.notebook.edit('color','Blue');s.controller.receive(s.update());const expected={sessionId:kind==='session'?'old':'s1',notebookSession:kind==='epoch'?2:1,revision:kind==='revision'?0:1};expect(s.controller.edit('color','Red',expected)).toBe(false);expect(s.controller.confirm('color',expected)).toBe(false);expect(s.socket.send).not.toHaveBeenCalled();expect(s.controller.snapshot().notes!.notes.color.value).toBe('Blue');s.controller.stop();});
});
