import {describe,it,expect} from 'vitest';
import {FIELDS,NotebookState,checkFixture} from '../src/notebook-state.ts';
import type {Field} from '../src/notebook-state.ts';
const candidate={occasion:'Outdoor wedding',season:'November',color:'Emerald green',style:'Elegant',lookType:'Dress',newItemCents:32000,currency:'USD' as const,excludedColors:[]};
function ready(){const s=new NotebookState();const values:Partial<Record<Field,string>>={occasion:'Outdoor wedding',season:'November; season not specified',color:'Emerald green',style:'Elegant',budget:'USD 350 maximum (items only)',lookType:'Dress'};for(const [id,value]of Object.entries(values))s.edit(id as Field,value);return s;}
describe('local notebook prototype',()=>{
 it('starts with seven explicitly missing values',()=>{const s=new NotebookState();expect(FIELDS).toHaveLength(7);expect(Object.values(s.snapshot().notes).every(n=>n.status==='missing')).toBe(true);expect(s.canPresent()).toBe(false);});
 it('captures clauses progressively before a turn finishes',()=>{const s=new NotebookState(),initial=s.snapshot();expect(s.capture({session:initial.session,field:'occasion',baseRevision:0,sequence:1,value:'Outdoor wedding',confirmed:true})).toBe(true);expect(s.snapshot().notes.occasion.value).toBe('Outdoor wedding');expect(s.snapshot().notes.color.status).toBe('missing');s.capture({session:initial.session,field:'color',baseRevision:0,sequence:2,value:'Emerald green',confirmed:false});expect(s.snapshot().notes.color.status).toBe('tentative');});
 it('does not infer a season or budget meaning from ambiguous speech',()=>{const s=new NotebookState();s.capture({session:1,field:'season',baseRevision:0,sequence:1,value:'November; season not specified',confirmed:false});s.capture({session:1,field:'budget',baseRevision:0,sequence:2,value:'500; currency and meaning to confirm',confirmed:false});expect(s.snapshot().notes.season.status).toBe('tentative');expect(s.snapshot().notes.budget.status).toBe('tentative');});
 it('keeps a touch edit when an older extraction arrives',()=>{const s=new NotebookState();s.edit('budget','USD 350 maximum (items only)');expect(s.capture({session:1,field:'budget',baseRevision:0,sequence:10,value:'USD 500 maximum (items only)',confirmed:true})).toBe(false);expect(s.snapshot().notes.budget.value).toContain('350');});
 it('keeps a voice correction when the old result arrives later',()=>{const s=ready(),before=s.snapshot();const event={session:before.session,field:'budget' as const,baseRevision:before.notes.budget.revision,sequence:3,value:'USD 300 maximum (items only)',confirmed:true};expect(s.capture(event)).toBe(true);expect(s.capture({...event,sequence:2,value:'USD 500 maximum (items only)'})).toBe(false);expect(s.snapshot().notes.budget.value).toContain('300');});
 it('rejects events from a cleared session',()=>{const s=new NotebookState();const event={session:1,field:'color' as const,baseRevision:0,sequence:1,value:'Green',confirmed:true};s.clear();expect(s.capture(event)).toBe(false);expect(s.snapshot().notes.color.status).toBe('missing');});
 it('invalidates checks on saved-fixture changes without confirming uncertain notes',()=>{const s=new NotebookState();s.capture({session:1,field:'color',baseRevision:0,sequence:1,value:'Emerald green',confirmed:false});const ticket=s.beginCheck();s.preferencesChanged();expect(s.completeCheck(ticket,{outcome:'passed',reason:'Old'})).toBe(false);expect(s.snapshot().notes.color.status).toBe('tentative');});
 it('returns independent copies of notes and references',()=>{const s=ready();s.setReference({label:'My jacket',kind:'owned'});const snap=s.snapshot();snap.notes.color.value='Wrong';snap.reference!.label='Wrong';expect(s.snapshot().notes.color.value).toBe('Emerald green');expect(s.snapshot().reference!.label).toBe('My jacket');});
 it('does not reveal a candidate until its matching check passes',()=>{const s=ready(),ticket=s.beginCheck();expect(s.canPresent()).toBe(false);expect(s.completeCheck(ticket,checkFixture(s.snapshot(),candidate))).toBe(true);expect(s.canPresent()).toBe(true);});
 it.each(['blocked','unknown','bad'])('holds a %s result',outcome=>{const s=ready(),ticket=s.beginCheck();s.completeCheck(ticket,{outcome:outcome as 'blocked',reason:'Held'});expect(s.canPresent()).toBe(false);});
 it('holds an empty or malformed approval',()=>{const s=ready(),ticket=s.beginCheck();s.completeCheck(ticket,{outcome:'passed',reason:''});expect(s.canPresent()).toBe(false);});
 it('holds timeouts and rejects late successful results',()=>{const s=ready(),ticket=s.beginCheck();s.timeout(ticket);expect(s.completeCheck(ticket,{outcome:'passed',reason:'Late'})).toBe(false);expect(s.canPresent()).toBe(false);});
 it('invalidates pending and passed checks on edits',()=>{const s=ready(),old=s.beginCheck();s.edit('budget','USD 100 maximum (items only)');expect(s.completeCheck(old,{outcome:'passed',reason:'Old'})).toBe(false);const current=s.beginCheck();s.completeCheck(current,{outcome:'passed',reason:'Fixture'});s.edit('color','Blue');expect(s.canPresent()).toBe(false);});
 it('does not accept a superseded check at the same revision',()=>{const s=ready(),old=s.beginCheck(),current=s.beginCheck();expect(s.completeCheck(old,{outcome:'passed',reason:'Old'})).toBe(false);expect(s.completeCheck(current,{outcome:'passed',reason:'Current'})).toBe(true);});
 it('retains a confirmed reference through note edits and clears it on session end',()=>{const s=ready();s.setReference({label:'Still A',kind:'owned'});s.edit('color','Blue');s.beginCheck();expect(s.snapshot().reference!.label).toBe('Still A');s.clear();expect(s.snapshot().reference).toBeNull();});
 it('reference changes invalidate approval and unknown item matching holds the look',()=>{const s=ready(),ticket=s.beginCheck();s.completeCheck(ticket,{outcome:'passed',reason:'Fixture'});s.setReference({label:'My jacket',kind:'owned'});expect(s.canPresent()).toBe(false);expect(checkFixture(s.snapshot(),candidate).outcome).toBe('unknown');});
 it('blocks a saved color exclusion and an over-budget fixture',()=>{const s=ready();expect(checkFixture(s.snapshot(),{...candidate,excludedColors:['Emerald green']}).outcome).toBe('blocked');s.edit('budget','USD 100 maximum (items only)');expect(checkFixture(s.snapshot(),candidate).outcome).toBe('blocked');});
 it('does not approve uncertain notes, unknown prices, budget scopes or unsupported dates',()=>{const s=ready();expect(checkFixture(s.snapshot(),{...candidate,newItemCents:NaN}).outcome).toBe('unknown');s.edit('budget','Around 500');expect(checkFixture(s.snapshot(),candidate).outcome).toBe('unknown');s.edit('budget','USD 350 maximum (items only)');s.edit('season','Summer');expect(checkFixture(s.snapshot(),candidate).outcome).toBe('unknown');});
 it('holds unreasonable budget amounts',()=>{const s=ready();s.edit('budget','USD 999999999999999999 maximum (items only)');expect(checkFixture(s.snapshot(),candidate).outcome).toBe('unknown');});
 it('does not treat an owned wardrobe note as matched',()=>{const s=ready();s.edit('wardrobe','My black jacket');expect(checkFixture(s.snapshot(),candidate).outcome).toBe('unknown');});
});
