import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {NoteConnectionScope} from '../src/note-connection-scope.ts';
import {NoteSessionProbe} from '../src/note-session-probe.ts';
import {NotebookState} from '../src/notebook-state.ts';
const owner={},other={};
const command=(sessionId:string,type='begin',sequence=1)=>type==='begin'?{version:1,sessionId,type,sequence,turnId:'turn1'}:{version:1,sessionId,type,sequence};
function setup(){let ended=false,reason='ended';const probe={audio:vi.fn(()=>true),edit:vi.fn(()=>true),confirm:vi.fn(()=>true),beginTurn:vi.fn(async()=>true),commit:vi.fn(()=>true),acknowledgeRendered:vi.fn(()=>true),receive:vi.fn(()=>true),end:vi.fn(()=>{ended=true;}),disconnected:vi.fn(()=>{ended=true;}),snapshot:()=>({ended,reason,transcription:null})};let serial=0;const create=vi.fn(()=>probe as any),scope=new NoteConnectionScope({simulation:true,create,id:()=>`session_${++serial}`});return{scope,probe,create,failCleanup:()=>{reason='cleanup-unverified';ended=true;}};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('simulated connection ownership boundary',()=>{
 it('refuses default live construction without creating resources',()=>{const create=vi.fn();expect(()=>new NoteConnectionScope({create})).toThrow('disabled');expect(create).not.toHaveBeenCalled();});
 it('admits one connection and rejects another tab even for the same user',()=>{const s=setup();expect(s.scope.open(owner)).toBe('session_1');expect(s.scope.open(other)).toBeNull();expect(s.scope.open(owner)).toBeNull();expect(s.create).toHaveBeenCalledTimes(1);});
 it('does not treat matching serialized identity as connection authority',async()=>{const s=setup(),a={user:'same'},b={user:'same'},id=s.scope.open(a)!;expect(await s.scope.command(b,command(id))).toBe(false);expect(s.scope.receive(b,id,{})).toBe(false);expect(s.scope.disconnect(b,id)).toBe(false);expect(s.probe.beginTurn).not.toHaveBeenCalled();});
 it('rejects guessed session IDs, duplicates and out-of-order commands',async()=>{const s=setup(),id=s.scope.open(owner)!;expect(await s.scope.command(owner,command('wrong'))).toBe(false);expect(await s.scope.command(owner,command(id))).toBe(true);expect(await s.scope.command(owner,command(id))).toBe(false);expect(await s.scope.command(owner,command(id,'commit',0))).toBe(false);expect(s.probe.beginTurn).toHaveBeenCalledTimes(1);});
 it.each(['extra','version','sequence','turn','type','receipt'])('holds malformed %s before touching the probe',async kind=>{const s=setup(),id=s.scope.open(owner)!,c:any=command(id);if(kind==='extra')c.owner='other';if(kind==='version')c.version=2;if(kind==='sequence')c.sequence=NaN;if(kind==='turn')c.turnId='../bad';if(kind==='type')c.type='provider';if(kind==='receipt'){delete c.turnId;c.type='rendered';c.receipt=-1;}expect(await s.scope.command(owner,c)).toBe(false);expect(s.probe.beginTurn).not.toHaveBeenCalled();});
 it('rejects old callbacks after ending and opening a new session',async()=>{const s=setup(),id=s.scope.open(owner)!;expect(await s.scope.command(owner,command(id,'end'))).toBe(true);expect(s.scope.receive(owner,id,{})).toBe(false);expect(await s.scope.command(owner,command(id,'commit',2))).toBe(false);});
 it('does not release a pending start into an ended session',async()=>{const s=setup(),id=s.scope.open(owner)!;let resolve!:(v:boolean)=>void;s.probe.beginTurn.mockImplementation(()=>new Promise(r=>{resolve=r;}));const pending=s.scope.command(owner,command(id));expect(await s.scope.command(owner,command(id,'end',2))).toBe(true);resolve(true);expect(await pending).toBe(false);});
 it('holds cleanup failure instead of admitting another session',()=>{const s=setup(),id=s.scope.open(owner)!;s.failCleanup();expect(s.scope.open(other)).toBeNull();expect(s.scope.receive(owner,id,{})).toBe(false);expect(s.scope.snapshot().held).toBe(true);});
 it('reserves the slot before reentrant resource construction',()=>{let scope!:NoteConnectionScope;const s=setup();scope=new NoteConnectionScope({simulation:true,create:()=>{expect(scope.open(other)).toBeNull();return s.probe as any;}});expect(scope.open(owner)).toBeTruthy();});
 it('holds failed construction and never retries automatically',()=>{const create=vi.fn(()=>{throw Error('private sentinel');}),scope=new NoteConnectionScope({simulation:true,create});expect(scope.open(owner)).toBeNull();expect(scope.open(other)).toBeNull();expect(create).toHaveBeenCalledTimes(1);expect(JSON.stringify(scope.snapshot())).not.toContain('sentinel');});
 it('closes once and prevents future opens',()=>{const s=setup();s.scope.open(owner);s.scope.close();s.scope.close();expect(s.probe.end).toHaveBeenCalledTimes(1);expect(s.scope.open(other)).toBeNull();});
 it('keeps old session callbacks isolated after a fresh session starts',async()=>{const probes:ReturnType<typeof setup>['probe'][]=[];let serial=0;const scope=new NoteConnectionScope({simulation:true,create:()=>{const p=setup().probe;probes.push(p);return p as any;},id:()=>`s${++serial}`});const old=scope.open(owner)!;await scope.command(owner,command(old,'end'));const fresh=scope.open(other)!;expect(fresh).not.toBe(old);expect(scope.receive(owner,old,{})).toBe(false);expect(scope.disconnect(owner,old)).toBe(false);expect(await scope.command(other,command(fresh))).toBe(true);expect(probes[1]!.end).not.toHaveBeenCalled();scope.close();});
 it('rejects repeated session identities without constructing a new probe',async()=>{const s=setup(),scope=new NoteConnectionScope({simulation:true,create:s.create,id:()=> 'same'}),id=scope.open(owner)!;await scope.command(owner,command(id,'end'));expect(scope.open(other)).toBeNull();expect(s.create).toHaveBeenCalledTimes(1);});
 it('still permits ending after reaching the command bound',async()=>{const s=setup(),id=s.scope.open(owner)!;for(let i=1;i<=256;i++)expect(await s.scope.command(owner,command(id,'commit',i))).toBe(true);expect(await s.scope.command(owner,command(id,'commit',257))).toBe(false);expect(await s.scope.command(owner,command(id,'end',258))).toBe(true);expect(s.scope.snapshot().active).toBe(false);});
 it('cannot reopen when construction itself closes the scope',()=>{const s=setup();let scope!:NoteConnectionScope;scope=new NoteConnectionScope({simulation:true,create:()=>{scope.close();return s.probe as any;}});expect(scope.open(owner)).toBeNull();expect(s.probe.end).toHaveBeenCalledTimes(1);expect(scope.snapshot().active).toBe(false);});
 it('never exposes connection identities, IDs or content in diagnostics',()=>{const s=setup();s.scope.open({privateIdentity:'private sentinel'});expect(JSON.stringify(s.scope.snapshot())).not.toMatch(/sentinel|session_1/);});
 it('binds a real simulated note session to one connection and clears notes on disconnect',async()=>{const notebook=new NotebookState(),close=vi.fn(),scope=new NoteConnectionScope({simulation:true,create:()=>new NoteSessionProbe({simulation:true,notebook,capture:{start:async()=>true,stop:vi.fn()},wire:{bufferedAmount:0,send:()=>true,close},extract:async()=>[{field:'color',value:'green',evidence:'green',confirmed:false}],changed:vi.fn()})}),id=scope.open(owner)!;scope.receive(owner,id,{type:'session.updated',session:{type:'transcription',audio:{input:{format:{type:'audio/pcm',rate:24000},transcription:{model:'gpt-live-transcribe'},turn_detection:null}}}});expect(await scope.command(owner,command(id))).toBe(true);const delta={type:'conversation.item.input_audio_transcription.delta',event_id:'ev1',item_id:'item1',content_index:0,delta:'green'};expect(scope.receive(other,id,delta)).toBe(false);expect(notebook.snapshot().notes.color.status).toBe('missing');expect(scope.receive(owner,id,delta)).toBe(true);await vi.advanceTimersByTimeAsync(100);expect(notebook.snapshot().notes.color.value).toBe('green');expect(scope.disconnect(owner,id)).toBe(true);expect(notebook.snapshot().notes.color.status).toBe('missing');expect(close).toHaveBeenCalledTimes(1);expect(scope.receive(owner,id,delta)).toBe(false);expect(scope.snapshot().active).toBe(false);});
});

describe('customer note commands through connection ownership',()=>{
 it('routes edit and confirm with the exact expected revision',async()=>{const s=setup(),id=s.scope.open(owner)!;expect(await s.scope.command(owner,{version:1,sessionId:id,sequence:1,type:'edit',field:'budget',value:'USD 350',expectedRevision:2})).toBe(true);expect(s.probe.edit).toHaveBeenCalledWith('budget','USD 350',2);expect(await s.scope.command(owner,{version:1,sessionId:id,sequence:2,type:'confirm',field:'color',expectedRevision:3})).toBe(true);expect(s.probe.confirm).toHaveBeenCalledWith('color',3);s.scope.close();});
 it.each(['field','revision','length','extra','owner'])('refuses invalid edit %s before mutation',async kind=>{const s=setup(),id=s.scope.open(owner)!,c:any={version:1,sessionId:id,sequence:1,type:'edit',field:'color',value:'Blue',expectedRevision:0};if(kind==='field')c.field='profile';if(kind==='revision')c.expectedRevision=-1;if(kind==='length')c.value='x'.repeat(161);if(kind==='extra')c.confirmed=true;expect(await s.scope.command(kind==='owner'?other:owner,c)).toBe(false);expect(s.probe.edit).not.toHaveBeenCalled();s.scope.close();});
 it('does not replay a rejected stale command or change another field',async()=>{const s=setup(),id=s.scope.open(owner)!;s.probe.edit.mockReturnValue(false);const c={version:1,sessionId:id,sequence:1,type:'edit',field:'color',value:'Blue',expectedRevision:0};expect(await s.scope.command(owner,c)).toBe(false);expect(await s.scope.command(owner,c)).toBe(false);expect(s.probe.edit).toHaveBeenCalledTimes(1);s.scope.close();});
});

describe('connection-bound audio authority',()=>{
 it('rejects a foreign or retired audio sender before the source receives frames',async()=>{const s=setup(),id=s.scope.open(owner)!,frame=new ArrayBuffer(968);expect(s.scope.audio(other,id,frame)).toBe(false);expect(s.scope.audio(owner,'wrong',frame)).toBe(false);expect(s.probe.audio).not.toHaveBeenCalled();expect(s.scope.audio(owner,id,frame)).toBe(true);expect(s.probe.audio).toHaveBeenCalledTimes(1);await s.scope.command(owner,command(id,'end'));expect(s.scope.audio(owner,id,frame)).toBe(false);expect(s.probe.audio).toHaveBeenCalledTimes(1);});
});
