import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {createPreparedNoteProviderSession} from '../src/prepared-note-provider-session.ts';
import {NotebookState,FIELDS,checkFixture} from '../src/notebook-state.ts';
import type {Field} from '../src/notebook-state.ts';
import {NOTE_EXTRACTION_MODEL} from '../src/openai-note-extractor.ts';
import {TRANSCRIPTION_MODEL} from '../src/live-transcription.ts';
const owners:ReturnType<typeof createPreparedNoteProviderSession>[]=[];
beforeEach(()=>vi.useFakeTimers());afterEach(()=>{owners.splice(0).forEach(o=>o.end());vi.useRealTimers();});
const values:Record<Field,string>={occasion:'outdoor wedding',season:'November; season not specified',color:'emerald green',style:'structured',budget:'USD 500 maximum (items only)',lookType:'dress',wardrobe:'black heels'};
const candidate={occasion:values.occasion,color:values.color,style:values.style,lookType:values.lookType,newItemCents:40000,currency:'USD' as const,excludedColors:[]};
function setup(){
 const notebook=new NotebookState(),provider=Object.assign(new EventTarget(),{readyState:1,bufferedAmount:0,send:vi.fn(),close:vi.fn()});let frame!:(pcm:ArrayBuffer)=>boolean;
 const event=(data:unknown)=>provider.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(data)}));let patches:{field:Field;value:string;evidence:string}[]=[];
 const fetch=vi.fn(async(_url:string,init:RequestInit)=>{const input=JSON.parse(JSON.parse(init.body as string).input[0].content[0].text);return Response.json({model:NOTE_EXTRACTION_MODEL,status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify({version:1,turnId:input.turnId,patches})}]}]});});
 const owner=createPreparedNoteProviderSession({simulation:true,notebook,socket:provider,fetch,signal:new AbortController().signal,capture:{start:async f=>{frame=f;return true;},stop:vi.fn()},changed:vi.fn()});owners.push(owner);
 event({type:'session.updated',session:{type:'transcription',audio:{input:{format:{type:'audio/pcm',rate:24000},transcription:{model:TRANSCRIPTION_MODEL},turn_detection:null}}}});
 async function turn(index:number,next:Partial<Record<Field,string>>){patches=Object.entries(next).map(([field,value])=>({field:field as Field,value:value!,evidence:value!}));const text=Object.values(next).join(', ');expect(await owner.probe.beginTurn(`t${index}`)).toBe(true);for(let i=0;i<5;i++)expect(frame(new ArrayBuffer(960))).toBe(true);event({type:'conversation.item.input_audio_transcription.delta',event_id:`d${index}`,item_id:`i${index}`,content_index:0,delta:text});await vi.advanceTimersByTimeAsync(100);expect(owner.probe.commit()).toBe(true);event({type:'input_audio_buffer.committed',event_id:`c${index}`,item_id:`i${index}`});event({type:'conversation.item.input_audio_transcription.completed',event_id:`f${index}`,item_id:`i${index}`,content_index:0,transcript:text});await vi.advanceTimersByTimeAsync(100);}
 return{notebook,owner,turn};
}
describe('complete preference extraction and fixture release checks',()=>{
 it('captures all seven literal fields as tentative and holds the sample until confirmation',async()=>{const s=setup();await s.turn(1,values);for(const [field] of FIELDS)expect(s.notebook.snapshot().notes[field]).toMatchObject({value:values[field],status:'tentative',source:'speech'});expect(checkFixture(s.notebook.snapshot(),candidate).outcome).toBe('unknown');for(const [field] of FIELDS)expect(s.owner.probe.confirm(field,s.notebook.snapshot().notes[field].revision)).toBe(true);expect(checkFixture(s.notebook.snapshot(),candidate)).toMatchObject({outcome:'unknown',reason:expect.stringContaining('Owned items')});expect(s.notebook.canPresent()).toBe(false);});
 it('invalidates a passed sample immediately on a spoken budget correction and rejects the old result',async()=>{const s=setup();await s.turn(1,values);for(const [field] of FIELDS)expect(s.owner.probe.confirm(field,s.notebook.snapshot().notes[field].revision)).toBe(true);expect(s.owner.probe.edit('wardrobe','',s.notebook.snapshot().notes.wardrobe.revision)).toBe(true);const old=s.notebook.beginCheck();expect(s.notebook.completeCheck(old,checkFixture(s.notebook.snapshot(),candidate))).toBe(true);expect(s.notebook.canPresent()).toBe(true);await s.turn(2,{budget:'USD 350 maximum (items only)'});expect(s.notebook.snapshot().notes.budget).toMatchObject({value:'USD 350 maximum (items only)',status:'tentative'});expect(s.notebook.canPresent()).toBe(false);expect(s.notebook.completeCheck(old,{outcome:'passed',reason:'stale'})).toBe(false);expect(checkFixture(s.notebook.snapshot(),candidate).outcome).toBe('unknown');expect(s.owner.probe.confirm('budget',s.notebook.snapshot().notes.budget.revision)).toBe(true);expect(checkFixture(s.notebook.snapshot(),candidate)).toMatchObject({outcome:'blocked',reason:expect.stringContaining('exceeds')});expect(s.notebook.canPresent()).toBe(false);});
 it('preserves ambiguous timing and dollars without inventing season, currency or missing values',async()=>{const s=setup();await s.turn(1,{season:'November',budget:'$500'});expect(s.notebook.snapshot().notes.season).toMatchObject({value:'November',status:'tentative'});expect(s.notebook.snapshot().notes.budget).toMatchObject({value:'$500',status:'tentative'});for(const field of ['occasion','color','style','lookType','wardrobe'] as const)expect(s.notebook.snapshot().notes[field].status).toBe('missing');expect(checkFixture(s.notebook.snapshot(),candidate).outcome).toBe('unknown');});
});
