import {describe,expect,it} from 'vitest';
import {decodeNoteAudio,encodeNoteAudio} from '../src/note-audio-frame.ts';
import {PreparedRemoteNoteCapture} from '../src/note-remote-capture.ts';
import {vi} from 'vitest';
describe('bounded simulated notebook audio',()=>{
 it('copies exact PCM frames and sequence numbers in both directions',()=>{const pcm=new ArrayBuffer(960);new Uint8Array(pcm)[0]=42;const frame=encodeNoteAudio(pcm,12);new Uint8Array(pcm)[0]=0;const result=decodeNoteAudio(frame);expect(result.sequence).toBe(12);expect(new Uint8Array(result.pcm)[0]).toBe(42);new Uint8Array(frame)[8]=0;expect(new Uint8Array(result.pcm)[0]).toBe(42);});
 it.each([-1,0.5,NaN,4250])('rejects an invalid frame sequence %s',sequence=>{expect(()=>encodeNoteAudio(new ArrayBuffer(960),sequence)).toThrow('held');});
 it.each([0,959,961])('rejects an incorrect PCM size %s',size=>{expect(()=>encodeNoteAudio(new ArrayBuffer(size),0)).toThrow('held');});
 it('rejects an incorrect wire size, version and sequence bound',()=>{expect(()=>decodeNoteAudio(new ArrayBuffer(960))).toThrow('held');const frame=encodeNoteAudio(new ArrayBuffer(960),0);new DataView(frame).setUint32(0,2);expect(()=>decodeNoteAudio(frame)).toThrow('held');const overflow=encodeNoteAudio(new ArrayBuffer(960),0);new DataView(overflow).setUint32(4,4250);expect(()=>decodeNoteAudio(overflow)).toThrow('held');});
 it('requires explicit simulation without acquiring anything',()=>{expect(()=>new PreparedRemoteNoteCapture({})).toThrow('disabled');});
 it('accepts only while acquired and keeps order across turn commits',async()=>{const capture=new PreparedRemoteNoteCapture({simulation:true}),accept=vi.fn(()=>true),stopped=vi.fn();expect(capture.receive(encodeNoteAudio(new ArrayBuffer(960),0))).toBe(false);expect(await capture.start(accept,stopped)).toBe(true);expect(await capture.start(accept,stopped)).toBe(false);expect(capture.receive(encodeNoteAudio(new ArrayBuffer(960),0))).toBe(true);capture.stop();expect(capture.receive(encodeNoteAudio(new ArrayBuffer(960),1))).toBe(false);expect(await capture.start(accept,stopped)).toBe(true);expect(capture.receive(encodeNoteAudio(new ArrayBuffer(960),1))).toBe(true);expect(capture.snapshot().frames).toBe(2);expect(stopped).not.toHaveBeenCalled();capture.end();expect(await capture.start(accept,stopped)).toBe(false);});
 it.each(['replay','gap','malformed','consumer'])('ends permanently on %s without retaining audio',async kind=>{const capture=new PreparedRemoteNoteCapture({simulation:true}),accept=vi.fn(()=>true),stopped=vi.fn();await capture.start(accept,stopped);capture.receive(encodeNoteAudio(new ArrayBuffer(960),0));if(kind==='consumer')accept.mockReturnValue(false);const frame=kind==='malformed'?new ArrayBuffer(1):encodeNoteAudio(new ArrayBuffer(960),kind==='replay'?0:kind==='gap'?2:1);expect(capture.receive(frame)).toBe(false);expect(stopped).toHaveBeenCalledTimes(1);expect(capture.snapshot()).toMatchObject({ended:true,capturing:false});expect(capture.receive(frame)).toBe(false);expect(await capture.start(accept,stopped)).toBe(false);expect(Object.keys(capture.snapshot())).toEqual(['ended','capturing','frames','liveEnabled']);});
});
