import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {PreparedBrowserNoteSession} from '../src/note-browser-session.ts';
import {encodeNoteUpdate} from '../src/note-update-wire.ts';
import {NotebookState} from '../src/notebook-state.ts';
const ready={version:1,type:'ready',sessionId:'s1',simulation:true,liveEnabled:false};
function setup(){let frame!:(pcm:ArrayBuffer)=>boolean,ended!:(reason:string)=>void;const socket={send:vi.fn(),close:vi.fn(),bufferedAmount:0},capture={start:vi.fn(async(a:(pcm:ArrayBuffer)=>boolean,e:(reason:string)=>void)=>{frame=a;ended=e;return true;}),stop:vi.fn()},changed=vi.fn(),session=new PreparedBrowserNoteSession({simulation:true,socket,capture,changed});return{socket,capture,changed,session,frame:()=>frame(new ArrayBuffer(960)),lost:()=>ended('device-ended'),ack:(sequence=1)=>session.receive({version:1,type:'accepted',sessionId:'s1',sequence})};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('disabled browser capture orchestration',()=>{
 it('requires simulation before touching devices or transport',()=>{const capture={start:vi.fn(),stop:vi.fn()},socket={send:vi.fn(),close:vi.fn(),bufferedAmount:0};expect(()=>new PreparedBrowserNoteSession({capture,socket,changed:vi.fn()})).toThrow('disabled');expect(capture.start).not.toHaveBeenCalled();expect(socket.send).not.toHaveBeenCalled();});
 it('does not acquire before readiness or from an invalid start',async()=>{const s=setup();expect(await s.session.startTurn('t1')).toBe(false);s.session.receive(ready);expect(await s.session.startTurn('../bad')).toBe(false);expect(s.capture.start).not.toHaveBeenCalled();s.session.stop();});
 it('requests capture immediately and discards frames before begin acknowledgment',async()=>{const s=setup();s.session.receive(ready);const pending=s.session.startTurn('t1');expect(s.capture.start).toHaveBeenCalledTimes(1);expect(s.frame()).toBe(true);expect(s.socket.send).toHaveBeenCalledTimes(1);s.ack();await pending;expect(s.frame()).toBe(true);expect(s.socket.send).toHaveBeenCalledTimes(2);expect(s.session.snapshot().capturing).toBe(true);s.session.stop();});
 it('stops capture before commit and ignores its old callbacks',async()=>{const s=setup();s.session.receive(ready);await s.session.startTurn('t1');s.ack();s.capture.stop.mockImplementation(()=>{expect(s.socket.send).toHaveBeenCalledTimes(1);s.lost();});expect(s.session.commit()).toBe(true);expect(JSON.parse(s.socket.send.mock.calls[1]![0])).toMatchObject({type:'commit'});expect(s.frame()).toBe(false);expect(s.session.snapshot().ended).toBe(false);s.capture.stop.mockReset();s.session.stop();});
 it.each(['disconnect','hidden','timeout'])('releases a source acquired after %s and cannot restart',async reason=>{const s=setup();let resolve!:(v:boolean)=>void;s.capture.start.mockImplementation(()=>new Promise(r=>{resolve=r;}));s.session.receive(ready);const pending=s.session.startTurn('t1');if(reason==='disconnect')s.session.disconnected();if(reason==='hidden')s.session.hidden();if(reason==='timeout')await vi.advanceTimersByTimeAsync(5000);resolve(true);expect(await pending).toBe(false);expect(s.capture.stop).toHaveBeenCalledTimes(2);expect(s.socket.close).toHaveBeenCalledTimes(1);expect(await s.session.startTurn('t2')).toBe(false);});
 it('ends and clears notes after permission denial',async()=>{const s=setup();s.session.receive(ready);s.capture.start.mockResolvedValue(false);expect(await s.session.startTurn('t1')).toBe(false);expect(s.session.snapshot().ended).toBe(true);expect(s.changed).toHaveBeenLastCalledWith(null);});
 it('holds thrown acquisition and cleanup errors without exposing private text',async()=>{const s=setup();s.session.receive(ready);s.capture.start.mockRejectedValue(Error('private sentinel'));expect(await s.session.startTurn('t1')).toBe(false);expect(JSON.stringify(s.session.snapshot())).not.toContain('sentinel');const t=setup();t.session.receive(ready);await t.session.startTurn('t1');t.ack();t.capture.stop.mockImplementation(()=>{throw Error('private');});expect(t.session.commit()).toBe(false);expect(t.session.snapshot()).toMatchObject({ended:true,cleanupFailed:true});expect(t.socket.send).toHaveBeenCalledTimes(1);});
 it('stops on device loss and on malformed connection input',async()=>{const s=setup();s.session.receive(ready);await s.session.startTurn('t1');s.ack();s.lost();expect(s.session.snapshot().ended).toBe(true);expect(s.frame()).toBe(false);const t=setup();t.session.receive(ready);await t.session.startTurn('t1');t.session.receive({type:'accepted'});expect(t.session.snapshot().ended).toBe(true);expect(t.capture.stop).toHaveBeenCalled();});
 it('does not stop or commit while permission or acknowledgment is pending',async()=>{const s=setup();s.session.receive(ready);const pending=s.session.startTurn('t1');expect(s.session.commit()).toBe(false);await pending;expect(s.session.commit()).toBe(false);s.ack();expect(s.session.commit()).toBe(true);s.ack(2);expect(await s.session.startTurn('t2')).toBe(false);s.session.stop();});
 it('ends on UI failure and clears the local connection',()=>{const s=setup();s.session.receive(ready);s.changed.mockImplementation(()=>{throw Error('private');});const notes=new NotebookState();notes.edit('color','green');s.session.receive(encodeNoteUpdate('s1',1,notes.snapshot(),null));expect(s.session.snapshot().ended).toBe(true);expect(s.session.snapshot().connection.notes).toBeNull();expect(s.socket.close).toHaveBeenCalledTimes(1);});
});

describe('capture during note commands',()=>{
 it('continues forwarding frames while an edit acknowledgment is pending',async()=>{const s=setup();s.session.receive(ready);const notebook=new NotebookState();notebook.edit('color','green');s.session.receive(encodeNoteUpdate('s1',1,notebook.snapshot(),null));await s.session.startTurn('t1');s.ack();expect(s.session.edit('color','Blue')).toBe(true);expect(s.frame()).toBe(true);expect(s.socket.send.mock.calls.at(-1)![0]).toBeInstanceOf(ArrayBuffer);s.session.stop();});
});

describe('subsequent simulated capture turns',()=>{
 it('starts another device acquisition only after matching provider readiness',async()=>{const s=setup();s.session.receive(ready);await s.session.startTurn('t1');s.ack();s.session.commit();s.ack(2);expect(await s.session.startTurn('t2')).toBe(false);expect(s.capture.start).toHaveBeenCalledTimes(1);s.session.receive({version:1,type:'turn-ready',sessionId:'s1',turnId:'t1'});expect(await s.session.startTurn('t2')).toBe(true);s.ack(3);expect(s.frame()).toBe(true);expect(s.capture.start).toHaveBeenCalledTimes(2);s.session.stop();});
});

describe('redacted simulated session status',()=>{
 it('distinguishes connecting, ready and capture before acknowledgment',async()=>{const s=setup();expect(s.session.status().state).toBe('connecting');s.session.receive(ready);expect(s.session.status().state).toBe('ready');const pending=s.session.startTurn('t1');expect(s.session.status().state).toBe('requesting-device');await pending;expect(s.session.status().state).toBe('waiting-turn');s.ack();expect(s.session.status().state).toBe('capturing');s.session.stop();});
 it('keeps processing status after command acknowledgment until final readiness',async()=>{const s=setup();s.session.receive(ready);await s.session.startTurn('t1');s.ack();s.session.commit();expect(s.session.status().state).toBe('processing');s.ack(2);expect(s.session.status().state).toBe('processing');s.session.receive({version:1,type:'turn-ready',sessionId:'s1',turnId:'t1'});expect(s.session.status().state).toBe('ready');s.session.stop();});
 it.each(['hidden','disconnected'] as const)('preserves the first local %s cause after repeated stops',method=>{const s=setup();s.session[method]();const status=s.session.status();s.session.stop();s.session.receive({private:'sentinel'});expect(s.session.status()).toEqual(status);expect(status.state).toBe('ended');expect(status.message.toLowerCase()).toContain('temporary notes');});
 it('does not echo a device error and reports cleanup uncertainty honestly',async()=>{const s=setup();s.session.receive(ready);s.capture.start.mockRejectedValue(Error('private device sentinel'));s.capture.stop.mockImplementation(()=>{throw Error('private cleanup sentinel');});await s.session.startTurn('t1');expect(s.session.status().state).toBe('cleanup-held');expect(s.session.status().message).toContain('could not be confirmed');expect(JSON.stringify(s.session.status())).not.toContain('sentinel');});
 it('reports a connection failure without claiming remote deletion',async()=>{const s=setup();await vi.advanceTimersByTimeAsync(5000);expect(s.session.status()).toEqual({state:'ended',message:'The connection ended. Temporary notes were cleared.'});expect(s.session.snapshot().status).toEqual(s.session.status());});
});
