import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {NotebookState} from '../src/notebook-state.ts';
import {PartialNoteCoordinator} from '../src/partial-note-coordinator.ts';
import {LookRelease} from '../src/look-release.ts';
const event=(text:string,sequence:number,turnId='turn')=>({version:1,eventId:`${turnId}_${sequence}`,turnId,sequence,role:'user',text,final:false});
const patch=(value:string)=>[{field:'color',value,evidence:value,confirmed:false}];
function setup(){const notebook=new NotebookState(),invalidated=vi.fn(),changed=vi.fn(),extract=vi.fn(async(input:{text:string})=>input.text.includes('green')?patch('green'):input.text.includes('blue')?patch('blue'):[]),coordinator=new PartialNoteCoordinator({notebook,extract,changed,invalidated});return{notebook,invalidated,changed,extract,coordinator};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('revised speech evidence',()=>{
 it('clears removed evidence immediately before replacement extraction',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);s.coordinator.accept(event('a wedding',2));expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.invalidated).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.status).toBe('missing');s.coordinator.cancel();});
 it('accepts a replacement after retracting its own revision',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);s.coordinator.accept(event('blue',2));await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color).toMatchObject({value:'blue',status:'tentative'});s.coordinator.cancel();});
 it.each(['edit','confirm','clear'])('preserves customer %s during a rewrite',async action=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);if(action==='edit')s.notebook.edit('color','red');else if(action==='confirm')s.notebook.confirm('color');else s.notebook.edit('color','');const before=s.notebook.snapshot().notes.color;s.coordinator.accept(event('blue',2));await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color).toEqual(before);s.coordinator.cancel();});
 it('does not retract notes from an earlier turn',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);s.coordinator.accept(event('wedding',1,'next'));await vi.advanceTimersByTimeAsync(100);s.coordinator.accept(event('birthday',2,'next'));expect(s.notebook.snapshot().notes.color.value).toBe('green');s.coordinator.cancel();});
 it('keeps notes during a stable appended partial',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);s.coordinator.accept(event('green wedding',2));expect(s.notebook.snapshot().notes.color.value).toBe('green');expect(s.invalidated).not.toHaveBeenCalled();s.coordinator.cancel();});
 it('cancels an old render receipt when its evidence is revised',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);const receipt=s.changed.mock.calls[0]![0];s.coordinator.accept(event('blue',2));expect(s.coordinator.acknowledgeRendered(receipt)).toBe(false);expect(s.coordinator.snapshot().timing.canceled).toBe(1);s.coordinator.cancel();});
 it('revokes a look permit synchronously on evidence retraction',async()=>{const s=setup(),release=new LookRelease(s.notebook);s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);const ticket=release.begin({id:'sample',description:'green look'});const permit=release.complete(ticket,{outcome:'passed',reason:'fixture'});expect(permit).not.toBeNull();s.coordinator.accept(event('blue',2));expect(release.visual(permit!)).toBeNull();release.dispose();s.coordinator.cancel();});
 it('does not revive a session cleared by its invalidation callback',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);s.invalidated.mockImplementation(()=>{s.notebook.clear();s.coordinator.cancel();});expect(s.coordinator.accept(event('blue',2))).toBe(false);await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.extract).toHaveBeenCalledTimes(1);});
 it('holds a failed invalidation display callback',async()=>{const s=setup();s.coordinator.accept(event('green',1));await vi.advanceTimersByTimeAsync(100);s.invalidated.mockImplementation(()=>{throw Error('private');});expect(s.coordinator.accept(event('blue',2))).toBe(false);expect(s.changed).toHaveBeenLastCalledWith(null);expect(s.notebook.snapshot().notes.color.status).toBe('missing');s.coordinator.cancel();});
 it('rejects retraction against another session, revision or touch source',()=>{const notebook=new NotebookState();notebook.capture({session:1,field:'color',baseRevision:0,sequence:1,value:'green',confirmed:false});expect(notebook.retractSpeech(2,'color',1)).toBe(false);expect(notebook.retractSpeech(1,'color',0)).toBe(false);notebook.confirm('color');expect(notebook.retractSpeech(1,'color',2)).toBe(false);});
});
