import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {createNotebookRehearsal} from '../src/note-browser-rehearsal.ts';
const owners:ReturnType<typeof createNotebookRehearsal>[]=[];
function setup(){const page=new EventTarget(),visibility=Object.assign(new EventTarget(),{hidden:false}),changed=vi.fn(),status=vi.fn(),clarificationChanged=vi.fn();const owner=createNotebookRehearsal({simulation:true,page,visibility,changed,status,clarificationChanged});owners.push(owner);return{owner,page,visibility,changed,status,clarificationChanged};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>{owners.splice(0).forEach(o=>o.dispose());vi.useRealTimers();});
describe('local notebook connection rehearsal',()=>{
 it('rejects activation without simulation',()=>{expect(()=>createNotebookRehearsal({page:new EventTarget(),visibility:Object.assign(new EventTarget(),{hidden:false}),changed:vi.fn(),status:vi.fn()})).toThrow('disabled');});
 it('runs two turns through the prepared owners and confirms the correction',async()=>{
   const s=setup();expect(s.owner.session.status().state).toBe('ready');expect(await s.owner.play()).toBe(true);await vi.advanceTimersByTimeAsync(1500);
   expect(s.changed.mock.lastCall![0].notes.color).toMatchObject({value:'Emerald green',status:'tentative'});expect(s.owner.session.status().state).toBe('ready');
   expect(await s.owner.play()).toBe(true);await vi.advanceTimersByTimeAsync(1500);expect(s.changed.mock.lastCall![0].notes.color).toMatchObject({value:'Blue',status:'tentative'});
   expect(s.owner.session.confirm('color')).toBe(true);await vi.advanceTimersByTimeAsync(50);expect(s.changed.mock.lastCall![0].notes.color.status).toBe('confirmed');
   expect(await s.owner.play()).toBe(false);expect(s.owner.snapshot().server?.transcription?.audioBytes).toBe(9600);s.owner.dispose();expect(s.changed).toHaveBeenLastCalledWith(null);expect(s.owner.snapshot().notes.notes.color.status).toBe('missing');expect(vi.getTimerCount()).toBe(0);
 });
 it('holds duplicate play while the first turn is pending',async()=>{const s=setup();expect(await s.owner.play()).toBe(true);expect(await s.owner.play()).toBe(false);expect(s.owner.turns()).toBe(1);});
 it.each(['pagehide','hidden','dispose'])('clears both owners on %s without late updates',async kind=>{const s=setup();await s.owner.play();if(kind==='pagehide')s.page.dispatchEvent(new Event('pagehide'));if(kind==='hidden'){s.visibility.hidden=true;s.visibility.dispatchEvent(new Event('visibilitychange'));}if(kind==='dispose')s.owner.dispose();await vi.advanceTimersByTimeAsync(2000);expect(s.owner.snapshot().closed).toBe(true);expect(s.owner.snapshot().server?.ended).toBe(true);expect(s.owner.session.snapshot().connection.notes).toBeNull();expect(s.changed).toHaveBeenLastCalledWith(null);expect(vi.getTimerCount()).toBe(0);});
 it('starts no capture and schedules no work on an already hidden page',()=>{const changed=vi.fn();const owner=createNotebookRehearsal({simulation:true,page:new EventTarget(),visibility:Object.assign(new EventTarget(),{hidden:true}),changed,status:vi.fn()});owners.push(owner);expect(owner.snapshot().closed).toBe(true);expect(owner.snapshot().server).toBeNull();expect(vi.getTimerCount()).toBe(0);});
 it('does not acquire browser media or fetch any provider',async()=>{const fetch=vi.spyOn(globalThis,'fetch');const s=setup();await s.owner.play();await vi.advanceTimersByTimeAsync(1500);expect(fetch).not.toHaveBeenCalled();fetch.mockRestore();});
});


describe('local connection preference presentation',()=>{
 it('requires confirmed notes and clears the scripted explanation on correction and end',async()=>{const s=setup();expect(s.owner.explain()).toBe(false);await s.owner.play();await vi.advanceTimersByTimeAsync(1500);expect(s.owner.explain()).toBe(false);s.owner.session.confirm('color');await vi.advanceTimersByTimeAsync(50);expect(s.owner.explain()).toBe(true);expect(s.clarificationChanged.mock.lastCall![0]).toMatchObject({issues:[{field:'color',reason:'request-conflict'}]});expect(s.owner.snapshot().notes.gate?.state).toBe('held');await s.owner.play();expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);await vi.advanceTimersByTimeAsync(1500);s.owner.session.confirm('color');await vi.advanceTimersByTimeAsync(50);expect(s.owner.explain()).toBe(true);s.owner.dispose();expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);expect(s.owner.explain()).toBe(false);expect(vi.getTimerCount()).toBe(0);});
 it.each(['pagehide','hidden'])('clears a held explanation on %s',async kind=>{const s=setup();await s.owner.play();await vi.advanceTimersByTimeAsync(1500);s.owner.session.confirm('color');await vi.advanceTimersByTimeAsync(50);s.owner.explain();if(kind==='pagehide')s.page.dispatchEvent(new Event('pagehide'));else{s.visibility.hidden=true;s.visibility.dispatchEvent(new Event('visibilitychange'));}expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);expect(s.owner.session.snapshot().connection.clarification).toBeNull();expect(vi.getTimerCount()).toBe(0);});
});


describe('multiple-field clarification rehearsal',()=>{
 async function confirmed(){const s=setup();await s.owner.play();await vi.advanceTimersByTimeAsync(1500);s.owner.session.confirm('color');await vi.advanceTimersByTimeAsync(50);return s;}
 it('shows three distinct issues without confirming style or inventing a budget',async()=>{const s=await confirmed();expect(s.owner.explain('multiple')).toBe(true);expect(s.owner.session.snapshot().connection.clarification?.issues).toEqual([{field:'color',reason:'request-conflict'},{field:'style',reason:'confirm-note'},{field:'budget',reason:'saved-uncertain'}]);expect(s.changed.mock.lastCall![0].notes.style).toMatchObject({value:'Structured',status:'tentative'});expect(s.changed.mock.lastCall![0].notes.budget).toMatchObject({value:'',status:'missing'});expect(s.owner.snapshot().notes.gate?.state).toBe('held');});
 it('replaces issues across rapid revisions without carrying earlier fields forward',async()=>{const s=await confirmed();s.owner.explain('multiple');const old=s.owner.session.snapshot().connection.clarification!;expect(s.owner.revise()).toBe(true);expect(s.owner.revise()).toBe(true);const latest=s.owner.session.snapshot().connection.clarification!;expect(latest.profileRevision).toBe(3);expect(latest.notebookRevision).toBeGreaterThan(old.notebookRevision);expect(latest.checkId).toBeGreaterThan(old.checkId);expect(latest.issues).toEqual([{field:'style',reason:'saved-uncertain'}]);expect(s.owner.session.snapshot().ended).toBe(false);s.owner.dispose();expect(s.owner.revise()).toBe(false);expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);});
 it('refuses simulated revisions before a current explanation exists',async()=>{const s=await confirmed();expect(s.owner.revise()).toBe(false);expect(s.owner.session.snapshot().connection.clarification).toBeNull();});
});

describe('connected revision-bound touch edits',()=>{
 it('clears the explanation before acknowledgment and publishes confirmed touch values only after acceptance',async()=>{const s=setup();await s.owner.play();await vi.advanceTimersByTimeAsync(1500);s.owner.session.confirm('color');await vi.advanceTimersByTimeAsync(50);s.owner.explain('multiple');const notes=s.owner.session.snapshot().connection.notes!;expect(s.owner.session.edit('style','Tailored',{sessionId:notes.sessionId,notebookSession:notes.notebookSession,revision:notes.notes.style.revision})).toBe(true);expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);expect(s.changed.mock.lastCall![0].notes.style.value).toBe('Structured');await vi.advanceTimersByTimeAsync(50);expect(s.changed.mock.lastCall![0].notes.style).toMatchObject({value:'Tailored',status:'confirmed',source:'touch'});expect(s.owner.snapshot().notes.gate?.state).not.toBe('passed');});
 it('refuses a stale draft without replacing a later correction',async()=>{const s=setup();const old=s.owner.session.snapshot().connection.notes!;await s.owner.play();await vi.advanceTimersByTimeAsync(1500);expect(s.owner.session.edit('color','Red',{sessionId:old.sessionId,notebookSession:old.notebookSession,revision:old.notes.color.revision})).toBe(false);expect(s.owner.snapshot().notes.notes.color.value).toBe('Emerald green');expect(s.owner.session.snapshot().ended).toBe(false);});
 it('drops a queued edit on connection loss and refuses later confirmation',async()=>{const s=setup();expect(s.owner.session.edit('budget','USD 350 maximum (items only)')).toBe(true);s.owner.session.disconnected();await vi.advanceTimersByTimeAsync(50);expect(s.changed).toHaveBeenLastCalledWith(null);expect(s.owner.snapshot().notes.notes.budget.status).toBe('missing');expect(s.owner.session.confirm('budget')).toBe(false);expect(vi.getTimerCount()).toBe(0);});
});

describe('deliberate local editor failure checks',()=>{
 it('replaces the server note while refusing the original draft and permits explicit review',async()=>{const s=setup();const old=s.owner.session.snapshot().connection.notes!;const version={sessionId:old.sessionId,notebookSession:old.notebookSession,revision:old.notes.color.revision};expect(s.owner.replaceWhileEditing('color')).toBe(true);expect(s.changed.mock.lastCall![0].notes.color).toMatchObject({value:'Blue',status:'tentative'});expect(s.owner.session.edit('color','Red',version)).toBe(false);const latest=s.owner.session.snapshot().connection.notes!;expect(s.owner.session.edit('color','Blue',{...version,revision:latest.notes.color.revision})).toBe(true);await vi.advanceTimersByTimeAsync(50);expect(s.owner.snapshot().notes.notes.color).toMatchObject({value:'Blue',status:'confirmed'});});
 it('disconnects with an unsent draft and clears the connection, notes and scheduled work',async()=>{const s=setup();const old=s.owner.session.snapshot().connection.notes!;s.owner.replaceWhileEditing('style');s.owner.disconnect();expect(s.owner.snapshot().closed).toBe(true);expect(s.owner.session.status()).toMatchObject({state:'ended',message:'The connection ended. Temporary notes were cleared.'});expect(s.changed).toHaveBeenLastCalledWith(null);expect(s.owner.session.edit('style','Unsent draft',{sessionId:old.sessionId,notebookSession:old.notebookSession,revision:old.notes.style.revision})).toBe(false);expect(s.owner.replaceWhileEditing('style')).toBe(false);expect(vi.getTimerCount()).toBe(0);});
 it('holds local replacements while a command is pending and refuses unknown fields',async()=>{const s=setup();expect(s.owner.replaceWhileEditing('profile' as any)).toBe(false);s.owner.session.edit('color','Green');expect(s.owner.replaceWhileEditing('color')).toBe(false);await vi.advanceTimersByTimeAsync(50);expect(s.owner.snapshot().notes.notes.color.value).toBe('Green');});
 it('leaves a scripted budget correction tentative and clears an old explanation',async()=>{const s=setup();s.owner.session.edit('color','Green');await vi.advanceTimersByTimeAsync(50);s.owner.explain('multiple');expect(s.owner.replaceWhileEditing('budget')).toBe(true);expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);expect(s.owner.snapshot().notes.notes.budget).toMatchObject({value:'USD 250 maximum (items only)',status:'tentative'});expect(s.owner.snapshot().notes.gate?.state).not.toBe('passed');});
});


describe('connection rehearsal timing lifecycle',()=>{
 const empty={total:0,rendered:0,failed:0,canceled:0,pending:0,overflow:0,p95Ms:null,liveTargetVerified:false};
 async function unacknowledged(){const s=setup();await s.owner.play();await vi.advanceTimersByTimeAsync(1500);return s;}
 it('keeps an unacknowledged display pending without inventing a duration',async()=>{const s=await unacknowledged();expect(s.owner.snapshot().server?.notes.timing).toEqual({...empty,total:1,pending:1});await vi.advanceTimersByTimeAsync(5000);expect(s.owner.snapshot().server?.notes.timing).toEqual({...empty,total:1,pending:1});});
 it('counts a replaced unacknowledged update as canceled and refuses its late receipt',async()=>{const s=await unacknowledged();const old=s.owner.session.snapshot().connection.notes!;expect(s.owner.replaceWhileEditing('color')).toBe(true);expect(s.owner.snapshot().server?.notes.timing).toEqual({...empty,total:1,canceled:1});expect(s.owner.session.rendered(old.sequence)).toBe(false);expect(s.owner.snapshot().server?.notes.timing).toEqual({...empty,total:1,canceled:1});});
 it('counts only a current acknowledged display as rendered, once',async()=>{const s=await unacknowledged();const note=s.owner.session.snapshot().connection.notes!;expect(s.owner.session.rendered(note.sequence)).toBe(true);await vi.advanceTimersByTimeAsync(50);expect(s.owner.snapshot().server?.notes.timing).toMatchObject({total:1,rendered:1,pending:0,canceled:0,liveTargetVerified:false});expect(s.owner.snapshot().server?.notes.timing.p95Ms).not.toBeNull();s.owner.session.rendered(note.sequence);await vi.advanceTimersByTimeAsync(50);expect(s.owner.snapshot().server?.notes.timing.rendered).toBe(1);});
 it.each(['dispose','disconnect','pagehide'])('isolates timing after %s and a replacement rehearsal',async kind=>{const old=await unacknowledged();const note=old.owner.session.snapshot().connection.notes!;if(kind==='dispose')old.owner.dispose();else if(kind==='disconnect')old.owner.disconnect();else old.page.dispatchEvent(new Event('pagehide'));expect(old.owner.session.snapshot().connection.notes).toBeNull();expect(old.owner.snapshot().server?.notes.timing).toEqual({...empty,total:1,canceled:1});expect(vi.getTimerCount()).toBe(0);const fresh=setup();expect(fresh.owner.snapshot().server?.notes.timing).toEqual(empty);expect(old.owner.session.rendered(note.sequence)).toBe(false);await vi.advanceTimersByTimeAsync(2000);expect(fresh.owner.snapshot().server?.notes.timing).toEqual(empty);expect(fresh.changed.mock.lastCall![0].notes.color.status).toBe('missing');fresh.owner.dispose();expect(vi.getTimerCount()).toBe(0);});
});
