import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {NoteBrowserController} from '../src/note-browser-controller.ts';
import {PreparedBrowserNoteSession} from '../src/note-browser-session.ts';
import {NotebookState} from '../src/notebook-state.ts';
import {encodeNoteUpdate} from '../src/note-update-wire.ts';
const ready={version:1,type:'ready',sessionId:'fixture',simulation:true,liveEnabled:false};
function setup(){
 const socket={send:vi.fn(),close:vi.fn(),bufferedAmount:0},changed=vi.fn(),clarificationChanged=vi.fn(),notebook=new NotebookState();notebook.edit('color','green');
 const controller=new NoteBrowserController({simulation:true,socket,changed,clarificationChanged});controller.receive(ready);
 const notes=(sequence=1)=>encodeNoteUpdate('fixture',sequence,notebook.snapshot(),null);controller.receive(notes());
 const message={version:1,type:'clarification',sessionId:'fixture',sequence:1,record:{version:1,profileRevision:2,notebookSession:1,notebookRevision:notebook.snapshot().revision,checkId:2,issues:[{field:'color',reason:'request-conflict'}]}};
 return{controller,socket,changed,clarificationChanged,notebook,notes,message};
}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('simulated browser clarification integration',()=>{
 it('delivers only a bound safe explanation without granting look authority',()=>{const s=setup();expect(s.controller.receive(s.message)).toBe(true);expect(s.clarificationChanged).toHaveBeenLastCalledWith(s.message.record);expect(s.socket.send).not.toHaveBeenCalled();expect(s.controller.snapshot().clarification).toEqual(s.message.record);s.controller.stop();});
 it.each(['begin','edit','confirm'] as const)('clears before sending %s and refuses delayed restoration',command=>{const s=setup();s.controller.receive(s.message);s.socket.send.mockImplementation(()=>expect(s.controller.snapshot().clarification).toBeNull());const result=command==='begin'?s.controller.begin('turn'):command==='edit'?s.controller.edit('color','blue'):s.controller.confirm('color');expect(result).toBe(true);expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);expect(s.controller.receive({...s.message,sequence:2})).toBe(false);expect(s.controller.snapshot().ended).toBe(true);});
 it('reserves the command slot before notifying a reentrant presentation callback',()=>{const s=setup();s.controller.receive(s.message);s.clarificationChanged.mockImplementation(record=>{if(record===null)expect(s.controller.edit('color','red')).toBe(false);});expect(s.controller.edit('color','blue')).toBe(true);expect(s.socket.send).toHaveBeenCalledTimes(1);expect(JSON.parse(s.socket.send.mock.calls[0]![0])).toMatchObject({sequence:1,value:'blue'});s.controller.stop();});
 it('accepts an explicit server clear after local invalidation',()=>{const s=setup();s.controller.receive(s.message);s.controller.edit('color','blue');expect(s.controller.receive({...s.message,sequence:2,record:null})).toBe(true);expect(s.controller.snapshot().clarification).toBeNull();s.controller.stop();});
 it('allows a fresh explanation only after a newer note revision',()=>{const s=setup();s.controller.receive(s.message);s.controller.edit('color','blue');s.notebook.edit('color','blue');expect(s.controller.receive(s.notes(2))).toBe(true);expect(s.controller.receive({...s.message,sequence:2,record:{...s.message.record,notebookRevision:s.notebook.snapshot().revision,checkId:3}})).toBe(true);s.controller.stop();});
 it.each(['session','revision','profile','check','private','replay'])('ends and clears unsafe %s messages',kind=>{const s=setup();s.controller.receive(s.message);const next:any={...s.message,sequence:2,record:{...s.message.record}};if(kind==='session')next.sessionId='other';if(kind==='revision')next.record.notebookRevision++;if(kind==='profile')next.record.profileRevision=1;if(kind==='check')next.record.checkId=1;if(kind==='private')next.record.savedValue='private';if(kind==='replay')next.sequence=1;expect(s.controller.receive(next)).toBe(false);expect(s.controller.snapshot().notes).toBeNull();expect(s.controller.snapshot().clarification).toBeNull();expect(s.clarificationChanged).toHaveBeenLastCalledWith(null);expect(s.socket.close).toHaveBeenCalledTimes(1);});
 it('ends safely when the explanation renderer throws',()=>{const s=setup();s.clarificationChanged.mockImplementation(()=>{throw Error('UI');});expect(s.controller.receive(s.message)).toBe(false);expect(s.controller.snapshot().ended).toBe(true);expect(s.controller.snapshot().clarification).toBeNull();});
 it('clears on deadlines and does not carry records into a replacement controller',async()=>{const s=setup();s.controller.receive(s.message);await vi.advanceTimersByTimeAsync(85000);expect(s.controller.snapshot().clarification).toBeNull();expect(s.controller.receive(s.message)).toBe(false);const replacement=setup();expect(replacement.controller.snapshot().clarification).toBeNull();replacement.controller.stop();});
 it('forwards through the browser session and clears on page hiding',()=>{const s=setup();s.controller.stop();const clarificationChanged=vi.fn(),capture={start:vi.fn(async()=>true),stop:vi.fn()};const session=new PreparedBrowserNoteSession({simulation:true,socket:s.socket,capture,changed:vi.fn(),clarificationChanged});session.receive(ready);session.receive(s.notes());expect(session.receive(s.message)).toBe(true);expect(clarificationChanged).toHaveBeenLastCalledWith(s.message.record);session.hidden();expect(clarificationChanged).toHaveBeenLastCalledWith(null);expect(session.snapshot().connection.clarification).toBeNull();expect(capture.start).not.toHaveBeenCalled();});
});
