import {describe,it,expect} from 'vitest';
import {NotebookState} from '../src/notebook-state.ts';
import {encodeNoteUpdate,decodeNoteUpdate,NoteUpdateClient} from '../src/note-update-wire.ts';
const ready={version:1,type:'ready',sessionId:'session1',simulation:true,liveEnabled:false};
function sample(sequence=1){const notebook=new NotebookState();notebook.capture({session:1,field:'color',baseRevision:0,sequence:1,value:'not green',confirmed:false});return encodeNoteUpdate('session1',sequence,notebook.snapshot(),7);}
describe('notebook update wire and client state',()=>{
 it('sends seven literal notes without profile, gate, reference, photo or transcript data',()=>{const notebook=new NotebookState();notebook.setReference({label:'private sentinel',kind:'owned'});notebook.beginCheck();const update=encodeNoteUpdate('session1',1,notebook.snapshot(),null);expect(Object.keys(update.notes)).toHaveLength(7);expect(JSON.stringify(update)).not.toMatch(/sentinel|gate|reference|transcript/);});
 it('copies snapshots on both encode and client access',()=>{const client=new NoteUpdateClient(),update=sample();client.ready(ready);client.accept(update);update.notes.color.value='changed';const shown=client.snapshot()!;expect(shown.notes.color.value).toBe('not green');shown.notes.color.value='changed';expect(client.snapshot()!.notes.color.value).toBe('not green');});
 it.each(['extra','unknownField','authority','oversized','status','revision','source','missingValue','receipt'])('rejects malformed %s updates',kind=>{const update:any=sample();switch(kind){case'extra':update.transcript='private';break;case'unknownField':update.notes.password={};break;case'authority':update.notes.color.saveProfile=true;break;case'oversized':update.notes.color.value='x'.repeat(161);break;case'status':update.notes.color.status='saved';break;case'revision':update.revision=-1;break;case'source':update.notes.color.source=null;break;case'missingValue':update.notes.color.status='missing';break;default:update.receipt=0;}expect(()=>decodeNoteUpdate(update)).toThrow('held');});
 it('requires a single simulated ready event before accepting updates',()=>{const client=new NoteUpdateClient();expect(client.accept(sample())).toBe(false);expect(client.ready({...ready,liveEnabled:true})).toBe(false);expect(client.ready(ready)).toBe(true);expect(client.ready(ready)).toBe(false);expect(client.accept(sample())).toBe(true);});
 it('rejects another session, replayed messages, old revisions and notebook resets',()=>{const client=new NoteUpdateClient();client.ready(ready);client.accept(sample());for(const update of [sample(),{...sample(2),sessionId:'other'},{...sample(2),revision:0},{...sample(2),notebookSession:2}])expect(client.accept(update)).toBe(false);expect(client.snapshot()!.notes.color.value).toBe('not green');});
 it('allows a newer retraction snapshot to clear an obsolete note',()=>{const notebook=new NotebookState(),client=new NoteUpdateClient();client.ready(ready);notebook.capture({session:1,field:'color',baseRevision:0,sequence:1,value:'green',confirmed:false});client.accept(encodeNoteUpdate('session1',1,notebook.snapshot(),1));notebook.retractSpeech(1,'color',1);expect(client.accept(encodeNoteUpdate('session1',2,notebook.snapshot(),null))).toBe(true);expect(client.snapshot()!.notes.color.status).toBe('missing');});
 it('acknowledges only the current update with a real render receipt',()=>{const client=new NoteUpdateClient();client.ready(ready);client.accept(sample());expect(client.rendered(1,2)).toEqual({version:1,type:'rendered',sessionId:'session1',sequence:2,receipt:7});expect(client.rendered(1,3)).toBeNull();client.accept({...sample(2),receipt:null});expect(client.rendered(1,3)).toBeNull();expect(client.rendered(2,3)).toBeNull();});
 it('clears all note content and rejects late events after disconnect',()=>{const client=new NoteUpdateClient();client.ready(ready);client.accept(sample());client.disconnect();expect(client.snapshot()).toBeNull();expect(client.accept(sample(2))).toBe(false);expect(client.ready(ready)).toBe(false);expect(client.rendered(1,3)).toBeNull();});
 it('rejects a changed value without its own field revision and a regressed field',()=>{const client=new NoteUpdateClient();client.ready(ready);client.accept(sample());const changed=sample(2);changed.revision++;changed.notes.color.value='blue';expect(client.accept(changed)).toBe(false);changed.notes.color.revision=0;expect(client.accept(changed)).toBe(false);});
 it('treats markup as literal text rather than rendering it',()=>{const update=sample();update.notes.color.value='<img src=x onerror=alert(1)>';expect(decodeNoteUpdate(update).notes.color.value).toBe(update.notes.color.value);});
});
