import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {NotebookState} from '../src/notebook-state.ts';
import {NotebookPresentation} from '../src/notebook-presentation.ts';
import {PartialNoteCoordinator} from '../src/partial-note-coordinator.ts';
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('visible notebook presentation preparation',()=>{
 it('shows seven missing notes initially',()=>{const notebook=new NotebookState(),view=new NotebookPresentation().present(notebook.snapshot(),null)!;expect(Object.values(view.snapshot.notes)).toHaveLength(7);expect(Object.values(view.snapshot.notes).every(note=>note.status==='missing')).toBe(true);});
 it('preserves tentative capture and customer confirmation',()=>{const notebook=new NotebookState(),view=new NotebookPresentation();notebook.capture({session:1,field:'color',baseRevision:0,sequence:1,value:'not green',confirmed:false});expect(view.present(notebook.snapshot(),1)!.snapshot.notes.color).toMatchObject({value:'not green',status:'tentative'});notebook.confirm('color');expect(view.present(notebook.snapshot(),null)!.snapshot.notes.color).toMatchObject({value:'not green',status:'confirmed',source:'touch'});});
 it('does not mix reference metadata into note fields or drop local reference/gate controls',()=>{const notebook=new NotebookState();notebook.setReference({label:'A jacket',kind:'owned'});notebook.beginCheck();const source=notebook.snapshot(),result=new NotebookPresentation().present(source,null)!;expect(result.snapshot.reference).toEqual(source.reference);expect(result.snapshot.gate).toEqual(source.gate);expect(result.snapshot.notes.wardrobe.status).toBe('missing');});
 it('returns an independent displayed snapshot',()=>{const notebook=new NotebookState(),view=new NotebookPresentation(),result=view.present(notebook.snapshot(),null)!;result.snapshot.notes.color.value='mutation';expect(view.present(notebook.snapshot(),null)!.snapshot.notes.color.value).toBe('');expect(notebook.snapshot().notes.color.value).toBe('');});
 it('acknowledges exactly once for the committed current update',()=>{const notebook=new NotebookState(),view=new NotebookPresentation(),result=view.present(notebook.snapshot(),7)!;expect(view.rendered(result.sequence)).toBe(7);expect(view.rendered(result.sequence)).toBeNull();});
 it('rejects a superseded render callback after an edit',()=>{const notebook=new NotebookState(),view=new NotebookPresentation(),old=view.present(notebook.snapshot(),7)!;notebook.edit('budget','USD 350 maximum (items only)');view.present(notebook.snapshot(),null);expect(view.rendered(old.sequence)).toBeNull();});
 it('clears for a new notebook session and does not revive old receipts',()=>{const notebook=new NotebookState(),view=new NotebookPresentation();notebook.edit('color','blue');const old=view.present(notebook.snapshot(),7)!;notebook.clear();const fresh=view.present(notebook.snapshot(),null)!;expect(fresh.snapshot.notes.color.status).toBe('missing');expect(view.rendered(old.sequence)).toBeNull();});
 it('holds updates and render acknowledgments after disconnect',()=>{const notebook=new NotebookState(),view=new NotebookPresentation(),old=view.present(notebook.snapshot(),7)!;view.disconnect();expect(view.present(notebook.snapshot(),8)).toBeNull();expect(view.rendered(old.sequence)).toBeNull();});
 it('does not restore a retired notebook session or reuse its update sequence',()=>{const notebook=new NotebookState(),view=new NotebookPresentation(),old=notebook.snapshot(),before=view.present(old,7)!;notebook.clear();const after=view.present(notebook.snapshot(),8)!;expect(after.sequence).toBeGreaterThan(before.sequence);expect(view.present(old,9)).toBeNull();expect(view.rendered(before.sequence)).toBeNull();expect(view.rendered(after.sequence)).toBe(8);});
 it('rejects a regressed snapshot instead of showing old notes',()=>{const notebook=new NotebookState(),view=new NotebookPresentation(),old=notebook.snapshot();notebook.edit('color','blue');view.present(notebook.snapshot(),null);expect(view.present(old,null)).toBeNull();});
 it('connects partial extraction, visible values, receipt acknowledgment and touch corrections',async()=>{const notebook=new NotebookState(),view=new NotebookPresentation();let displayed:ReturnType<NotebookPresentation['present']>=null;const coordinator=new PartialNoteCoordinator({notebook,extract:async()=>[{field:'color',value:'green',evidence:'green',confirmed:false}],changed:receipt=>{displayed=view.present(notebook.snapshot(),receipt);}});coordinator.accept({version:1,eventId:'ev1',turnId:'turn1',sequence:1,role:'user',text:'green',final:false});await vi.advanceTimersByTimeAsync(100);const shown=displayed as unknown as NonNullable<ReturnType<NotebookPresentation['present']>>;expect(shown.snapshot.notes.color).toMatchObject({value:'green',status:'tentative'});expect(coordinator.acknowledgeRendered(view.rendered(shown.sequence)!)).toBe(true);notebook.edit('color','blue');expect(view.present(notebook.snapshot(),null)!.snapshot.notes.color.value).toBe('blue');coordinator.cancel();});
});
