import {describe,it,expect,vi} from 'vitest';
import {createPreparedNoteExtractionTransport,NOTE_EXTRACTION_ENDPOINT} from '../src/note-extraction-transport.ts';
import {buildOpenAINoteRequest,createPreparedOpenAINoteExtractor,NOTE_EXTRACTION_MODEL} from '../src/openai-note-extractor.ts';
const input={turnId:'t1',text:'green',context:''};
const body=buildOpenAINoteRequest(input);
function setup(response:Response|Promise<Response>=Response.json({ok:true})){const fetch=vi.fn(()=>Promise.resolve(response));const request=createPreparedNoteExtractionTransport({simulation:true,fetch});return{fetch,request,abort:new AbortController()};}
describe('disabled bounded extraction HTTP preparation',()=>{
 it('requires explicit simulation before any request',()=>{const fetch=vi.fn();expect(()=>createPreparedNoteExtractionTransport({fetch})).toThrow('disabled');expect(fetch).not.toHaveBeenCalled();});
 it('uses the exact endpoint, no-store, redirect rejection and no credentials',async()=>{const s=setup();expect(await s.request(body,s.abort.signal)).toEqual({ok:true});const [url,init]=s.fetch.mock.calls[0]! as unknown as [string,RequestInit];expect(url).toBe(NOTE_EXTRACTION_ENDPOINT);expect(init).toMatchObject({method:'POST',redirect:'error',cache:'no-store',signal:s.abort.signal,headers:{'Content-Type':'application/json'}});expect(init.headers).not.toHaveProperty('Authorization');expect(JSON.parse(init.body as string)).toMatchObject({model:NOTE_EXTRACTION_MODEL,store:false,tools:[]});expect(s.fetch).toHaveBeenCalledTimes(1);});
 it('rejects an oversized request before sending',async()=>{const s=setup();await expect(s.request({...body,instructions:'x'.repeat(32769)},s.abort.signal)).rejects.toThrow('unavailable');expect(s.fetch).not.toHaveBeenCalled();});
 it('rejects a redirected response',async()=>{const response=Response.json({ok:true});Object.defineProperty(response,'redirected',{value:true});const s=setup(response);await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');});
 it('rejects an unexpected response destination',async()=>{const response=Response.json({ok:true});Object.defineProperty(response,'url',{value:'https://example.com'});const s=setup(response);await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');});
 it.each([400,401,429,500])('holds HTTP %s without retry or exposing body',async status=>{const s=setup(new Response('private sentinel',{status}));await expect(s.request(body,s.abort.signal)).rejects.toThrow('Extraction transport unavailable.');expect(s.fetch).toHaveBeenCalledTimes(1);});
 it.each(['text/html','text/event-stream',''])('rejects content type %s',async type=>{const s=setup(new Response('{}',{headers:{'content-type':type}}));await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');});
 it.each(['32769','-1','private'])('rejects invalid declared response length %s',async length=>{const s=setup(new Response('{}',{headers:{'content-type':'application/json','content-length':length}}));await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');});
 it('bounds actual streamed bytes without trusting content-length',async()=>{const cancel=vi.fn(),stream=new ReadableStream<Uint8Array>({start(c){c.enqueue(new Uint8Array(32769));},cancel});const s=setup(new Response(stream,{headers:{'content-type':'application/json'}}));await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');expect(cancel).toHaveBeenCalled();});
 it.each(['not-json','{"private":"sentinel"'])('rejects malformed JSON without exposing it',async text=>{const s=setup(new Response(text,{headers:{'content-type':'application/json'}}));await expect(s.request(body,s.abort.signal)).rejects.toThrow('Extraction transport unavailable.');});
 it('holds invalid UTF-8',async()=>{const s=setup(new Response(new Uint8Array([255]),{headers:{'content-type':'application/json'}}));await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');});
 it('never requests after prior cancellation',async()=>{const s=setup();s.abort.abort();await expect(s.request(body,s.abort.signal)).rejects.toThrow('unavailable');expect(s.fetch).not.toHaveBeenCalled();});
 it('settles when an injected request ignores cancellation',async()=>{const s=setup(new Promise(()=>{}));const pending=s.request(body,s.abort.signal);s.abort.abort();await expect(pending).rejects.toThrow('unavailable');});
 it('cancels a response delivered after cancellation',async()=>{let resolve!:(response:Response)=>void;const cancel=vi.fn();const s=setup(new Promise<Response>(done=>{resolve=done;}));const pending=s.request(body,s.abort.signal);s.abort.abort();await expect(pending).rejects.toThrow('unavailable');resolve(new Response(new ReadableStream<Uint8Array>({cancel}),{headers:{'content-type':'application/json'}}));await Promise.resolve();await Promise.resolve();expect(cancel).toHaveBeenCalled();});
 it('cancels an unfinished response read on abort',async()=>{const cancel=vi.fn(),stream=new ReadableStream<Uint8Array>({cancel});const s=setup(new Response(stream,{headers:{'content-type':'application/json'}}));const pending=s.request(body,s.abort.signal);await Promise.resolve();await Promise.resolve();s.abort.abort();await expect(pending).rejects.toThrow('unavailable');expect(cancel).toHaveBeenCalled();});
 it('flows a completed pinned response through the existing extractor decoder',async()=>{const result={status:'completed',model:NOTE_EXTRACTION_MODEL,output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify({version:1,turnId:'t1',patches:[{field:'color',value:'green',evidence:'green'}]})}]}]};const s=setup(Response.json(result));const extract=createPreparedOpenAINoteExtractor({simulation:true,request:s.request});expect(await extract(input,s.abort.signal)).toEqual([{field:'color',value:'green',evidence:'green',confirmed:false}]);});
});
