import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {NotebookState} from '../src/notebook-state.ts';
import {PartialNoteCoordinator} from '../src/partial-note-coordinator.ts';
import {NoteTiming} from '../src/note-timing.ts';
const event=(text='green',sequence=1,turnId='turn')=>({version:1,eventId:`${turnId}_${sequence}`,turnId,sequence,role:'user',text,final:false});
const patch=(value='Green',evidence='green')=>[{field:'color',value,evidence,confirmed:true}];
function setup(extract:(input:{text:string},signal:AbortSignal)=>Promise<unknown>=async()=>patch(),syntheticFixture=false){const notebook=new NotebookState(),changed=vi.fn();const coordinator=new PartialNoteCoordinator({notebook,extract,changed,syntheticFixture,clock:()=>Date.now()});return{notebook,changed,coordinator};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>vi.useRealTimers());
describe('partial notes with synthetic extraction',()=>{
 it('captures before final and keeps real adapter output tentative',async()=>{const s=setup();s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.status).toBe('tentative');expect(s.coordinator.acknowledgeRendered(s.changed.mock.calls[0]![0])).toBe(true);});
 it('permits explicitly synthetic confirmation',async()=>{const s=setup(undefined,true);s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.status).toBe('confirmed');});
 it('rejects duplicate, stale, assistant and extra-key events',()=>{const s=setup();expect(s.coordinator.accept(event())).toBe(true);for(const value of [event(),event('x',0),{...event('x',2),role:'assistant'},{...event('x',3),authority:true}])expect(s.coordinator.accept(value)).toBe(false);});
 it('flushes within 400ms despite continuous partials',async()=>{const extract=vi.fn(async()=>patch()),s=setup(extract);for(let i=1;i<=8;i++){s.coordinator.accept(event('green',i));await vi.advanceTimersByTimeAsync(50);}expect(extract).toHaveBeenCalledTimes(1);});
 it('coalesces appended clauses while a job runs',async()=>{let release!:(v:unknown)=>void;const inputs:string[]=[];const s=setup(async input=>{inputs.push(input.text);return inputs.length===1?await new Promise(r=>{release=r;}):patch('Blue','blue');});s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);s.coordinator.accept(event('green blue',2));await vi.advanceTimersByTimeAsync(100);expect(inputs).toEqual(['green']);release(patch());await vi.advanceTimersByTimeAsync(100);expect(inputs).toEqual(['green','blue']);});
 it('protects touch edits throughout the same turn',async()=>{let release!:(v:unknown)=>void;const s=setup(async()=>new Promise(r=>{release=r;}));s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);s.notebook.edit('color','Red');release(patch());await vi.advanceTimersByTimeAsync(0);s.coordinator.accept(event('green blue',2));await vi.advanceTimersByTimeAsync(100);release(patch('Blue','blue'));await vi.advanceTimersByTimeAsync(0);expect(s.notebook.snapshot().notes.color.value).toBe('Red');});
 it('allows a later turn to correct an edit',async()=>{const s=setup();s.notebook.edit('color','Red');s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.value).toBe('Green');});
 it('ignores rewritten work and rejects retired turns',async()=>{let release!:(v:unknown)=>void;const s=setup(async()=>new Promise(r=>{release=r;}));s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);const old=release;s.coordinator.accept(event('blue',2));old(patch());await vi.advanceTimersByTimeAsync(0);expect(s.notebook.snapshot().notes.color.status).toBe('missing');s.coordinator.accept(event('red',1,'next'));expect(s.coordinator.accept(event('green',3))).toBe(false);});
 it.each(['field','evidence','duplicate','authority'])('rejects invalid %s patches atomically',async kind=>{const result=kind==='field'?[{...patch()[0],field:'unknown'}]:kind==='evidence'?[{...patch()[0],evidence:'absent'}]:kind==='duplicate'?[...patch(),...patch()]:[{...patch()[0],authority:true}];const s=setup(async()=>result);s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.coordinator.snapshot().failures).toBe(1);});
 it('times out without retry or transcript exposure',async()=>{const extract=vi.fn(async()=>new Promise(()=>{})),s=setup(extract);s.coordinator.accept(event('private green'));await vi.advanceTimersByTimeAsync(1700);expect(extract).toHaveBeenCalledTimes(1);expect(s.coordinator.snapshot().timing.failed).toBe(1);expect(JSON.stringify(s.coordinator.snapshot())).not.toContain('private');});
 it('rejects old render receipts after clearing or editing',async()=>{const s=setup();s.coordinator.accept(event());await vi.advanceTimersByTimeAsync(100);const id=s.changed.mock.calls[0]![0];s.notebook.edit('style','Structured');expect(s.coordinator.acknowledgeRendered(id)).toBe(false);s.notebook.clear();s.coordinator.reset();expect(s.coordinator.acknowledgeRendered(id)).toBe(false);});
});
describe('timing metadata',()=>{
 it('includes slow samples and reports incomplete work separately',()=>{let now=0;const t=new NoteTiming(()=>now);for(let i=0;i<20;i++){now=0;const id=t.begin(0)!;t.extracted(id);now=i<18?100:4000;t.rendered(id);}t.finish(t.begin(0)!,'failed');t.begin(0);expect(t.report()).toMatchObject({p95Ms:4000,rendered:20,failed:1,pending:1,liveTargetVerified:false});});
 it('bounds storage, copies results and never reuses cleared IDs',()=>{const t=new NoteTiming(()=>0),old=t.begin(0)!;for(let i=1;i<256;i++)t.begin(0);expect(t.begin(0)).toBeNull();t.records()[0]!.state='rendered';expect(t.report().pending).toBe(256);t.clear();expect(t.begin(0)).not.toBe(old);expect(t.rendered(old)).toBe(false);});
 it('rejects invalid clocks',()=>{const t=new NoteTiming(()=>-1),id=t.begin(0)!;expect(t.extracted(id)).toBe(false);expect(t.report().failed).toBe(1);});
});
