import {describe,it,expect} from 'vitest';
import {NotebookState} from '../src/notebook-state.ts';
import {encodeNoteUpdate} from '../src/note-update-wire.ts';
import {preparePreferenceClarification} from '../src/preference-clarification.ts';
import {decodeClarificationMessage,SimulatedClarificationClient} from '../src/preference-clarification-wire.ts';
function setup(){const notebook=new NotebookState();notebook.edit('color','green');const ticket=notebook.beginCheck();notebook.completeCheck(ticket,{outcome:'unknown',reason:'Clarify'});const record=preparePreferenceClarification({simulation:true,profileRevision:1,notebook:notebook.snapshot(),ticket,issues:[{field:'color',reason:'request-conflict'}]});const message={version:1,type:'clarification',sessionId:'fixture',sequence:1,record};const notes=encodeNoteUpdate('fixture',1,notebook.snapshot(),null);const client=new SimulatedClarificationClient({simulation:true});client.notes(notes);return{notebook,record,message,notes,client};}
describe('strict simulated clarification wire',()=>{
 it('requires explicit simulation',()=>expect(()=>new SimulatedClarificationClient({})).toThrow('disabled'));
 it('copies and freezes exact safe messages',()=>{const s=setup(),message=decodeClarificationMessage(s.message);expect(message).toEqual(s.message);expect(message).not.toBe(s.message);expect(Object.isFrozen(message.record?.issues[0])).toBe(true);});
 it.each(['savedValue','ruleId','permit','saveProfile'])('rejects private or authoritative record fields %s',key=>{const s=setup();expect(()=>decodeClarificationMessage({...s.message,record:{...s.record,[key]:'private'}})).toThrow('held');});
 it.each([0,-1,1.5,Number.MAX_SAFE_INTEGER+1])('rejects malformed sequence %j',sequence=>expect(()=>decodeClarificationMessage({...setup().message,sequence})).toThrow('held'));
 it.each([[],Array(36).fill({field:'color',reason:'request-conflict'}),[{field:'account',reason:'request-conflict'}],[{field:'color',reason:'override'}],[{field:'color',reason:'request-conflict',value:'private'}],[{field:'color',reason:'request-conflict'},{field:'color',reason:'request-conflict'}]].map(issues=>({issues})))('rejects unsafe issues $issues',({issues})=>{const s=setup();expect(()=>decodeClarificationMessage({...s.message,record:{...s.record,issues}})).toThrow('held');});
 it('accepts explicit clears while a local invalidation barrier holds',()=>{const s=setup();s.client.accept(s.message);s.client.clear();expect(s.client.accept({...s.message,sequence:2,record:null})).toBe(true);expect(s.client.accept({...s.message,sequence:3})).toBe(false);});
 it('accepts current records and explicit clears without changing notes',()=>{const s=setup();expect(s.client.accept(s.message)).toBe(true);expect(s.client.snapshot()).toEqual(s.record);expect(s.client.accept({...s.message,sequence:2,record:null})).toBe(true);expect(s.client.snapshot()).toBeNull();expect(s.notebook.snapshot().notes.color.value).toBe('green');});
 it.each(['session','notebook','revision','profile','check','sequence'])('rejects stale or mismatched %s bindings',kind=>{const s=setup();s.client.accept(s.message);const next={...s.message,sequence:2,record:{...s.record}};if(kind==='session')next.sessionId='other';if(kind==='notebook')next.record.notebookSession++;if(kind==='revision')next.record.notebookRevision++;if(kind==='profile')next.record.profileRevision=0;if(kind==='check')next.record.checkId=0;if(kind==='sequence')next.sequence=1;expect(s.client.accept(next)).toBe(false);expect(s.client.snapshot()).toBeNull();});
 it('clears on a newer notebook revision and rejects an old explanation',()=>{const s=setup();s.client.accept(s.message);s.notebook.edit('color','blue');expect(s.client.notes(encodeNoteUpdate('fixture',2,s.notebook.snapshot(),null))).toBe(true);expect(s.client.snapshot()).toBeNull();expect(s.client.accept({...s.message,sequence:2})).toBe(false);});
 it('rejects replacement identities, regressive notes and malformed notes',()=>{const s=setup();s.client.accept(s.message);expect(s.client.notes({...s.notes,sequence:2,sessionId:'replacement'})).toBe(false);expect(s.client.notes(s.notes)).toBe(false);expect(s.client.notes({})).toBe(false);expect(s.client.snapshot()).toBeNull();});
 it('clears locally and permanently ends without authorizing any action',()=>{const s=setup();s.client.accept(s.message);s.client.clear();expect(s.client.snapshot()).toBeNull();s.client.stop();expect(s.client.notes(s.notes)).toBe(false);expect(s.client.accept({...s.message,sequence:2})).toBe(false);expect(s.client.snapshot()).toBeNull();});
 it('does not restore a cleared explanation before a newer note revision',()=>{const s=setup();s.client.accept(s.message);s.client.clear();expect(s.client.accept({...s.message,sequence:2})).toBe(false);s.client.notes({...s.notes,sequence:2});expect(s.client.accept({...s.message,sequence:3})).toBe(false);s.notebook.edit('color','blue');s.client.notes(encodeNoteUpdate('fixture',3,s.notebook.snapshot(),null));expect(s.client.accept({...s.message,sequence:4,record:{...s.record,notebookRevision:s.notebook.snapshot().revision,checkId:2}})).toBe(true);});

});
