import {afterEach,describe,it,expect,vi} from 'vitest';
import {createPreparedNoteProviderSession} from '../src/prepared-note-provider-session.ts';
import {NotebookState} from '../src/notebook-state.ts';
import {NOTE_EXTRACTION_MODEL} from '../src/openai-note-extractor.ts';
import {TRANSCRIPTION_MODEL} from '../src/live-transcription.ts';
class Socket extends EventTarget{readyState=1;bufferedAmount=0;send=vi.fn();close=vi.fn();message(event:unknown){this.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(event)}));}}
const config={type:'session.updated',session:{type:'transcription',audio:{input:{format:{type:'audio/pcm',rate:24000},transcription:{model:TRANSCRIPTION_MODEL},turn_detection:null}}}};
function setup(fetch=vi.fn(async()=>Response.json({model:NOTE_EXTRACTION_MODEL,status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify({version:1,turnId:'t1',patches:[{field:'color',value:'green',evidence:'green'}]})}]}]}))){const socket=new Socket(),abort=new AbortController(),notebook=new NotebookState(),changed=vi.fn();let accept!:(pcm:ArrayBuffer)=>boolean;const capture={start:vi.fn(async(callback:(pcm:ArrayBuffer)=>boolean)=>{accept=callback;return true;}),stop:vi.fn(),end:vi.fn()};const options={simulation:true,socket,fetch,signal:abort.signal,notebook,capture,changed};const session=createPreparedNoteProviderSession(options);return{...options,abort,...session,audio:()=>accept(new ArrayBuffer(960))};}
afterEach(()=>vi.useRealTimers());
describe('combined disabled note provider preparation',()=>{
 it('requires explicit simulation before capture, send or extraction',()=>{const s=setup();s.end();const sent=s.socket.send.mock.calls.length;expect(()=>createPreparedNoteProviderSession({...s,simulation:false})).toThrow('disabled');expect(s.socket.send).toHaveBeenCalledTimes(sent);expect(s.fetch).not.toHaveBeenCalled();expect(s.capture.start).not.toHaveBeenCalled();});
 it('extracts partial notes and clears all owners on external cancellation',async()=>{vi.useFakeTimers();const s=setup();s.socket.message(config);expect(await s.probe.beginTurn('t1')).toBe(true);for(let i=0;i<5;i++)expect(s.audio()).toBe(true);s.socket.message({type:'conversation.item.input_audio_transcription.delta',event_id:'e1',item_id:'i1',content_index:0,delta:'green'});await vi.advanceTimersByTimeAsync(100);expect(s.notebook.snapshot().notes.color).toMatchObject({value:'green',status:'tentative'});s.abort.abort();s.end();expect(s.status()).toEqual({ended:true,cleanupFailed:false,liveEnabled:false});expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.capture.end).toHaveBeenCalledTimes(1);expect(s.socket.close).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);});
 it('cancels pending extraction on disconnect',async()=>{vi.useFakeTimers();let signal:AbortSignal|undefined;const fetch=vi.fn(async(_url?:string,init?:RequestInit)=>{signal=init?.signal as AbortSignal;return new Promise<Response>(()=>{});});const s=setup(fetch);s.socket.message(config);await s.probe.beginTurn('t1');s.socket.message({type:'conversation.item.input_audio_transcription.delta',event_id:'e1',item_id:'i1',content_index:0,delta:'green'});await vi.advanceTimersByTimeAsync(100);expect(signal?.aborted).toBe(false);s.socket.dispatchEvent(new Event('close'));expect(signal?.aborted).toBe(true);await vi.advanceTimersByTimeAsync(0);expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(s.status().ended).toBe(true);expect(vi.getTimerCount()).toBe(0);});
 it('closes the shared socket when extraction fails',async()=>{vi.useFakeTimers();const s=setup(vi.fn(async()=>{throw Error('private sentinel');}));s.socket.message(config);await s.probe.beginTurn('t1');s.socket.message({type:'conversation.item.input_audio_transcription.delta',event_id:'e1',item_id:'i1',content_index:0,delta:'green'});await vi.advanceTimersByTimeAsync(100);expect(s.status().ended).toBe(true);expect(s.socket.close).toHaveBeenCalledTimes(1);expect(s.notebook.snapshot().notes.color.status).toBe('missing');expect(JSON.stringify(s.status())).not.toContain('sentinel');expect(vi.getTimerCount()).toBe(0);});
 it('retains cleanup failure instead of claiming success',()=>{const s=setup();s.socket.close.mockImplementation(()=>{throw Error('private');});s.end();expect(s.status().cleanupFailed).toBe(true);});
 it('holds an already aborted session without sending configuration',()=>{const s=setup();s.end();s.abort.abort();const count=s.socket.send.mock.calls.length;const session=createPreparedNoteProviderSession({...s,signal:s.abort.signal});expect(session.status().ended).toBe(true);expect(s.socket.send).toHaveBeenCalledTimes(count);session.end();});
 it('reports final capture cleanup failure before notifying the connection owner',async()=>{const socket=new Socket(),notebook=new NotebookState(),observed:boolean[]=[],capture={start:async()=>true,stop:()=>{throw Error('private');},end:vi.fn()};let owner!:ReturnType<typeof createPreparedNoteProviderSession>;owner=createPreparedNoteProviderSession({simulation:true,socket,notebook,signal:new AbortController().signal,capture,fetch:async()=>Response.json({}),changed:vi.fn(),stopped:()=>{observed.push(owner.status().cleanupFailed);}});owner.probe.end();await Promise.resolve();expect(observed).toEqual([true]);expect(capture.end).toHaveBeenCalledTimes(1);expect(owner.status().cleanupFailed).toBe(true);});
});
