import {afterEach,describe,expect,it,vi} from 'vitest';
import {createPreparedNotePersistenceTransport} from '../src/prepared-note-persistence-transport.ts';
import type {PreparedNoteLedger} from '../src/prepared-note-allowance.ts';
const url='https://fixture.supabase.co';
const fixture=():PreparedNoteLedger=>({version:1,purpose:'notes-only-simulation',approval:{id:'synthetic',attempts:2,centsPerAttempt:100,secondsPerAttempt:85},runs:[]});
const opened=()=>({...fixture(),runs:[{id:'first',closed:false}]});
function setup(response:Response|Promise<Response>=Response.json(fixture())){const fetch=vi.fn(()=>Promise.resolve(response));return{fetch,transport:createPreparedNotePersistenceTransport({simulation:true,url,fetch})};}
afterEach(()=>vi.useRealTimers());
describe('disabled bounded notebook persistence transport',()=>{
 it('requires explicit simulation before requests',()=>{const fetch=vi.fn();expect(()=>createPreparedNotePersistenceTransport({url,fetch})).toThrow('disabled');expect(fetch).not.toHaveBeenCalled();});
 it.each(['http://fixture.supabase.co','https://example.com','https://fixture.supabase.co.evil.test','https://secret@fixture.supabase.co','https://fixture.supabase.co:444','https://fixture.supabase.co/other','https://fixture.supabase.co/?x=1','https://fixture.supabase.co/#private'])('rejects configuration %s',url=>{const fetch=vi.fn();expect(()=>createPreparedNotePersistenceTransport({simulation:true,url,fetch})).toThrow('requires review');expect(fetch).not.toHaveBeenCalled();});
 it('reads only the fixed notebook RPC with no keys, cookies or retries',async()=>{const s=setup();expect(await s.transport.read()).toEqual(fixture());const [target,init]=s.fetch.mock.calls[0]! as unknown as [string,RequestInit];expect(target).toBe(url+'/rest/v1/rpc/stylist_notebook_allowance_read');expect(init).toMatchObject({method:'POST',redirect:'error',cache:'no-store',credentials:'omit',body:'{}',headers:{'Content-Type':'application/json',Accept:'application/json'}});expect(init.signal?.aborted).toBe(false);expect(s.fetch).toHaveBeenCalledTimes(1);});
 it.each([true,false])('returns a strict compare-and-swap %s without retry',async result=>{const s=setup(Response.json(result));expect(await s.transport.compareAndSwap(fixture(),opened())).toBe(result);const [target,init]=s.fetch.mock.calls[0]! as unknown as [string,RequestInit];expect(target).toBe(url+'/rest/v1/rpc/stylist_notebook_allowance_change');expect(JSON.parse(init.body as string)).toEqual({expected:fixture(),replacement:opened()});expect(s.fetch).toHaveBeenCalledTimes(1);});
 it('rejects an invalid transition before sending',async()=>{const s=setup();await expect(s.transport.compareAndSwap(fixture(),fixture())).rejects.toThrow('unavailable');expect(s.fetch).not.toHaveBeenCalled();});
 it.each([null,[],{version:1,runs:[]},{...fixture(),private:'sentinel'}])('rejects invalid or legacy read data: %j',async value=>{const s=setup(Response.json(value));await expect(s.transport.read()).rejects.toThrow('Notebook persistence unavailable.');});
 it.each(['true',null,{ok:true},1])('rejects nonboolean write acknowledgments: %j',async value=>{const s=setup(Response.json(value));await expect(s.transport.compareAndSwap(fixture(),opened())).rejects.toThrow('unavailable');expect(s.fetch).toHaveBeenCalledTimes(1);});
 it.each([400,401,403,429,500])('holds HTTP %s without exposing its body',async status=>{const s=setup(new Response('private sentinel',{status}));await expect(s.transport.read()).rejects.toThrow('Notebook persistence unavailable.');expect(s.fetch).toHaveBeenCalledTimes(1);});
 it.each(['text/html','text/event-stream',''])('rejects content type %s',async type=>{const s=setup(new Response('{}',{headers:{'content-type':type}}));await expect(s.transport.read()).rejects.toThrow('unavailable');});
 it.each(['16385','-1','private'])('rejects declared content length %s',async length=>{const s=setup(new Response('{}',{headers:{'content-type':'application/json','content-length':length}}));await expect(s.transport.read()).rejects.toThrow('unavailable');});
 it.each(['redirected','url'])('rejects response %s changes',async field=>{const response=Response.json(fixture());Object.defineProperty(response,field,{value:field==='redirected'?true:'https://elsewhere.test'});await expect(setup(response).transport.read()).rejects.toThrow('unavailable');});
 it('bounds actual bytes and cancels an oversized stream',async()=>{const cancel=vi.fn(),body=new ReadableStream<Uint8Array>({start(c){c.enqueue(new Uint8Array(16385));},cancel});await expect(setup(new Response(body,{headers:{'content-type':'application/json'}})).transport.read()).rejects.toThrow('unavailable');expect(cancel).toHaveBeenCalled();});
 it.each([new TextEncoder().encode('not-json'),new Uint8Array([255])])('rejects malformed JSON or UTF-8',async bytes=>{await expect(setup(new Response(bytes,{headers:{'content-type':'application/json'}})).transport.read()).rejects.toThrow('unavailable');});
 it('times out an ignored request signal and cancels a late response body',async()=>{
  vi.useFakeTimers();let resolve!:(response:Response)=>void;const s=setup(new Promise<Response>(r=>{resolve=r;})),pending=s.transport.read(),check=expect(pending).rejects.toThrow('unavailable');await vi.advanceTimersByTimeAsync(8000);await check;
  const cancel=vi.fn();resolve(new Response(new ReadableStream<Uint8Array>({cancel}),{headers:{'content-type':'application/json'}}));await Promise.resolve();await Promise.resolve();expect(cancel).toHaveBeenCalled();expect(s.fetch).toHaveBeenCalledTimes(1);
 });
 it('times out a stalled response body and releases its reader',async()=>{vi.useFakeTimers();const cancel=vi.fn(),s=setup(new Response(new ReadableStream<Uint8Array>({cancel}),{headers:{'content-type':'application/json'}})),pending=s.transport.read(),check=expect(pending).rejects.toThrow('unavailable');await vi.advanceTimersByTimeAsync(8000);await check;expect(cancel).toHaveBeenCalled();expect(s.fetch).toHaveBeenCalledTimes(1);});
 it('redacts an injected failure without retry',async()=>{const s=setup(Promise.reject(Error('private sentinel')));await expect(s.transport.read()).rejects.toThrow('Notebook persistence unavailable.');expect(s.fetch).toHaveBeenCalledTimes(1);});
});
