import {describe,it,expect,vi} from 'vitest';
import {TRANSCRIPTION_CONNECTION_PLAN as plan,PreparedTranscriptionCloseEvidence} from '../src/transcription-connection-plan.ts';
const close=(extra:Record<string,unknown>={})=>({type:'close',connectionId:'fixture_1',code:1000,wasClean:true,...extra});
const create=()=>new PreparedTranscriptionCloseEvidence('fixture_1',{simulation:true});
describe('disabled transcription connection inspection',()=>{
 it('labels the proposed endpoint and keeps all activation gates closed',()=>{expect(plan.url).toBe('wss://api.openai.com/v1/realtime?model=gpt-live-transcribe');expect(plan).toMatchObject({startupEvidence:'ai-assisted-support-proposal',liveEnabled:false,startupVerified:false,remoteCleanupVerified:false,configurationEvent:'session.update',readinessEvent:'session.updated'});expect(Object.isFrozen(plan)).toBe(true);expect(JSON.stringify(plan)).not.toContain('session.start');expect(JSON.stringify(plan)).not.toContain('session.closed');});
 it('rejects live observation and invalid identities',()=>{expect(()=>new PreparedTranscriptionCloseEvidence('fixture_1',{})).toThrow('disabled');expect(()=>new PreparedTranscriptionCloseEvidence('',{simulation:true})).toThrow('identity');});
 it('starts with no closure or resource-release proof',()=>{expect(create().snapshot()).toEqual({transportClosed:false,normalCloseObserved:false,remoteCleanupVerified:false,finalUsageVerified:false,deletionVerified:false,mayReleaseAllowance:false});});
 it('records normal local close only after an explicit request',()=>{const evidence=create();expect(evidence.observe(close())).toBe(false);evidence.requestClose();expect(evidence.observe(close())).toBe(true);expect(evidence.snapshot()).toEqual({transportClosed:true,normalCloseObserved:true,remoteCleanupVerified:false,finalUsageVerified:false,deletionVerified:false,mayReleaseAllowance:false});expect(Object.isFrozen(evidence.snapshot())).toBe(true);});
 it.each([1001,1006,1011])('keeps abnormal code %s distinct from normal closure',code=>{const evidence=create();evidence.requestClose();expect(evidence.observe(close({code}))).toBe(true);expect(evidence.snapshot()).toMatchObject({transportClosed:true,normalCloseObserved:false,mayReleaseAllowance:false});});
 it('does not mistake an unclean normal-code event for a normal close',()=>{const evidence=create();evidence.requestClose();evidence.observe(close({wasClean:false}));expect(evidence.snapshot().normalCloseObserved).toBe(false);});
 it.each([null,[],{},close({connectionId:'old'}),close({type:'session.closed'}),close({code:'1000'}),close({code:NaN}),close({code:999}),close({code:5000}),close({wasClean:1}),close({remoteCleanupVerified:true})])('rejects malformed, other-protocol or wrong-owner evidence %#',value=>{const evidence=create();evidence.requestClose();expect(evidence.observe(value)).toBe(false);expect(evidence.snapshot().transportClosed).toBe(false);});
 it('cannot upgrade an abnormal result through a duplicate close',()=>{const evidence=create();evidence.requestClose();evidence.observe(close({code:1006,wasClean:false}));expect(evidence.observe(close())).toBe(false);expect(evidence.snapshot().normalCloseObserved).toBe(false);});
 it('isolates replacement identities and does not acquire a network connection',()=>{const network=vi.spyOn(globalThis,'fetch');const old=create();old.requestClose();old.observe(close());const fresh=new PreparedTranscriptionCloseEvidence('fixture_2',{simulation:true});fresh.requestClose();expect(fresh.observe(close())).toBe(false);expect(fresh.snapshot().transportClosed).toBe(false);expect(network).not.toHaveBeenCalled();network.mockRestore();});
});
