import { echoAudio, interruptAvatar, pcmDurationMs } from './contracts.ts';
import type { AudioFrame, Command, ResponseKey } from './contracts.ts';

export type SessionState = 'idle' | 'speaking' | 'stopped' | 'held' | 'ended';
type Active = ResponseKey & { deliveredMs: number; heardMs: number | null; generationDone: boolean; completionSent: boolean };

/** Single mutation authority. Actual transport delivery must separately be proven.
 * Passing generated bytes or a server speaking span as customer playback is forbidden.
 */
export class VoiceSession {
  private epoch = 0;
  private active: Active | null = null;
  private queue: AudioFrame[] = [];
  private seen = new Set<string>();
  private state: SessionState = 'idle';
  private reason = '';
  private delivered = 0;
  private rejected = 0;
  private conversationId: string;

  constructor(conversationId: string) { this.conversationId = conversationId; }

  start(responseId: string, itemId: string): ResponseKey {
    if (!responseId || !itemId) throw new Error('Response and item IDs are required');
    if (!['idle', 'stopped'].includes(this.state)) throw new Error('Stop or reset the current response first');
    this.epoch += 1;
    this.active = { epoch: this.epoch, responseId, itemId, deliveredMs: 0, heardMs: null, generationDone: false, completionSent: false };
    this.queue = []; this.seen.clear(); this.state = 'speaking'; this.reason = '';
    return { epoch: this.epoch, responseId, itemId };
  }

  private matches(key: ResponseKey): boolean {
    return this.active !== null && key.epoch === this.active.epoch && key.responseId === this.active.responseId && key.itemId === this.active.itemId;
  }

  enqueue(frame: AudioFrame): Command[] {
    if (!this.matches(frame) || this.state !== 'speaking' || this.active?.generationDone || this.seen.has(frame.eventId)) {
      this.rejected += 1; return [];
    }
    try { pcmDurationMs(frame.pcm); } catch { return this.hold('Malformed audio was held.'); }
    if (this.queue.length >= 50 || this.seen.size >= 500) return this.hold('Audio queue limit reached.');
    this.seen.add(frame.eventId); this.queue.push(frame); return [];
  }

  takeAudio(): Command[] {
    if (this.state !== 'speaking' || !this.active) return [];
    const frame = this.queue.shift();
    if (!frame) return [];
    this.active.deliveredMs += pcmDurationMs(frame.pcm); this.delivered += 1;
    return [echoAudio(this.conversationId, frame.responseId, frame.pcm), ...this.finishSendingAudio()];
  }

  acknowledgePlayback(key: ResponseKey, actuallyHeardMs: number): boolean {
    if (!this.matches(key) || this.state !== 'speaking' || !this.active || !Number.isFinite(actuallyHeardMs)
      || actuallyHeardMs < (this.active.heardMs ?? 0) || actuallyHeardMs > this.active.deliveredMs) {
      this.rejected += 1; return false;
    }
    this.active.heardMs = actuallyHeardMs; return true;
  }

  finishGeneration(key: ResponseKey, status: string): Command[] {
    if (!this.matches(key) || this.state !== 'speaking' || !this.active) { this.rejected += 1; return []; }
    // Audio-done is not evidence of successful generation or customer playback.
    if (status !== 'completed') return this.hold('Generation ended without successful completion.');
    this.active.generationDone = true;
    return this.finishSendingAudio();
  }

  // Tell the renderer there are no more chunks before waiting for playback.
  // Returning the command is not evidence of transport delivery or playback.
  private finishSendingAudio(): Command[] {
    if (!this.active || !this.active.generationDone || this.queue.length || this.active.completionSent) return [];
    this.active.completionSent = true;
    return [echoAudio(this.conversationId, this.active.responseId, '', true)];
  }

  finishPlayback(key: ResponseKey): Command[] {
    if (!this.matches(key) || !this.active || this.state !== 'speaking' || !this.active.generationDone
      || !this.active.completionSent || this.queue.length || this.active.heardMs === null || this.active.heardMs !== this.active.deliveredMs) {
      this.rejected += 1; return [];
    }
    this.active = null; this.state = 'stopped'; return [];
  }

  interrupt(): Command[] {
    if (!this.active || this.state !== 'speaking') return [];
    const active = this.active;
    // Invalidate before handing commands to a transport. Late callbacks cannot restart output.
    this.active = null; this.queue = []; this.seen.clear(); this.epoch += 1;
    const commands: Command[] = [
      { target: 'openai', payload: { type: 'response.cancel', response_id: active.responseId } },
      interruptAvatar(this.conversationId),
    ];
    if (active.heardMs === null) {
      this.state = 'held'; this.reason = 'Playback position is unknown. A new provider context is required.';
      commands.push({ target: 'coordinator', payload: { type: 'reset_realtime_context', reason: this.reason } });
    } else {
      this.state = 'stopped';
      commands.push({ target: 'openai', payload: {
        type: 'conversation.item.truncate', item_id: active.itemId, content_index: 0, audio_end_ms: Math.floor(active.heardMs),
      } });
    }
    return commands;
  }

  hold(reason: string): Command[] {
    const commands = this.interrupt(); this.state = 'held'; this.reason = reason; return commands;
  }

  end(): Command[] {
    const commands = this.interrupt();
    this.active = null; this.queue = []; this.seen.clear(); this.epoch += 1; this.state = 'ended'; return commands;
  }

  snapshot() {
    return { state: this.state, epoch: this.epoch, queued: this.queue.length, delivered: this.delivered, rejected: this.rejected, reason: this.reason };
  }
}
